#!/usr/bin/env python3
"""Make llasm COM glue and weak C stubs from interface lists (*.com files).

A .com file lists interfaces in vtable order:

    # comment
    interface IDirectPlay4A
        QueryInterface *riid *ppvObj
        AddRef
        Release
        Close                       = 0x80004001
        EnumConnections *guid cb ctx flags = 0

Each method becomes "proc <Iface>_<Method>_asm2c" (stdcall: reads "this"
and the parameters from the x86 stack, calls <Iface>_<Method>_c, pops
them) and an entry of the vtable "<Iface>Vtbl_asm2c". A leading "*" marks a
pointer parameter (a host pointer in C). A C function with the same name in
the runtime replaces the weak stub. A stub prints the method name once and
returns the value after "=" (default E_NOTIMPL, 0x80004001).

Usage: gen_com.py <output folder for .llasm> <output .c file> <spec.com>...
Writes com-<spec name>.llasm per spec, and one C file with all stubs.
"""

import os
import sys


def parse(path):
    ifaces = []
    for raw in open(path):
        line = raw.split("#")[0].rstrip()
        if not line.strip():
            continue
        words = line.split()
        if words[0] == "interface":
            ifaces.append((words[1], []))
            continue
        ret = "0x80004001"
        if "=" in words:
            i = words.index("=")
            ret = words[i + 1]
            words = words[:i]
        ifaces[-1][1].append((words[0], words[1:], ret))
    return ifaces


def main():
    outdir, cfile, specs = sys.argv[1], sys.argv[2], sys.argv[3:]
    stubs = ["/* Generated by common/tools/gen_com.py. Do not edit. */",
             "#include <stdint.h>", "#include <stdio.h>", ""]
    for spec in specs:
        base = os.path.splitext(os.path.basename(spec))[0]
        ifaces = parse(spec)
        out = [";; Generated by common/tools/gen_com.py from %s. Do not edit." % os.path.basename(spec),
               "", "include llasm.llinc", "include asm-calls.llinc", ""]
        for iface, methods in ifaces:
            for name, params, _ in methods:
                out.append("func %s_%s_c %s" % (iface, name, ", ".join(["*lpThis"] + params)))
            out.append("")
        for iface, methods in ifaces:
            for name, params, ret in methods:
                n = 1 + len(params)
                out.append("proc %s_%s_asm2c public" % (iface, name))
                regs = []
                for i in range(n):
                    out.append("        add tmp%d, esp, %d" % (i, 4 * (i + 1)))
                    out.append("        load tmp%d, tmp%d, 4" % (i, i))
                    regs.append("tmp%d" % i)
                out.append("        call %s_%s_c %s" % (iface, name, ", ".join(regs)))
                out.append("        mov eax, tmp0")
                out.append("        Call_Asm_Return %d" % n)
                out.append("endp")
                out.append("")
                stubs.append('__attribute__((weak)) uint32_t %s_%s_c(void) { static int once; '
                             'if (!once++) fprintf(stderr, "unimplemented: %s::%s\\n"); return %s; }'
                             % (iface, name, iface, name, ret))
        out.append("datasegment %s_com_data constant" % base.replace("-", "_"))
        out.append("")
        for iface, methods in ifaces:
            out.append("dlabel %sVtbl_asm2c global" % iface)
            for name, _, _ in methods:
                out.append("daddr %s_%s_asm2c" % (iface, name))
            out.append("")
        out.append("endd")
        with open(os.path.join(outdir, "com-%s.llasm" % base), "w") as fh:
            fh.write("\n".join(out) + "\n")
    with open(cfile, "w") as fh:
        fh.write("\n".join(stubs) + "\n")


if __name__ == "__main__":
    main()
