#!/usr/bin/env python3
"""Write llasm COM glue (method procs and vtables) for the video player.

Each method becomes "proc <Iface>_<Method>_asm2c" that reads the stdcall
parameters from the x86 stack, calls <Iface>_<Method>_c and pops them.
A leading "*" marks a pointer parameter (converted to a host pointer).
The vtable is "<Iface>Vtbl_asm2c".

Usage: gen_com_glue.py > runtime/llasm/WinApi-amstream-asm.llasm
"""

INTERFACES = [
    ("IAMMultiMediaStream", [
        ("QueryInterface", "*riid *ppvObject"),
        ("AddRef", ""),
        ("Release", ""),
        ("GetInformation", "*pdwFlags *pStreamType"),
        ("GetMediaStream", "*idPurpose *ppMediaStream"),
        ("EnumMediaStreams", "Index *ppMediaStream"),
        ("GetState", "*pCurrentState"),
        ("SetState", "NewState"),
        ("GetTime", "*pCurrentTime"),
        ("GetDuration", "*pDuration"),
        ("Seek", "SeekTimeLow SeekTimeHigh"),
        ("GetEndOfStreamEventHandle", "*phEOS"),
        ("Initialize", "StreamType dwFlags *pFilterGraph"),
        ("GetFilterGraph", "*ppGraphBuilder"),
        ("GetFilter", "*ppFilter"),
        ("AddMediaStream", "pStreamObject *PurposeId dwFlags *ppNewStream"),
        ("OpenFile", "*pszFileName dwFlags"),
        ("OpenMoniker", "*pCtx *pMoniker dwFlags"),
        ("Render", "dwFlags"),
    ]),
    ("IDirectDrawMediaStream", [
        ("QueryInterface", "*riid *ppvObject"),
        ("AddRef", ""),
        ("Release", ""),
        ("GetMultiMediaStream", "*ppMultiMediaStream"),
        ("GetInformation", "*pPurposeId *pType"),
        ("SetSameFormat", "pStreamThatHasDesiredFormat dwFlags"),
        ("AllocateSample", "dwFlags *ppSample"),
        ("CreateSharedSample", "pExistingSample dwFlags *ppNewSample"),
        ("SendEndOfStream", "dwFlags"),
        ("GetFormat", "*pDDSDCurrent *ppDirectDrawPalette *pDDSDDesired *pdwFlags"),
        ("SetFormat", "*pDDSurfaceDesc pDirectDrawPalette"),
        ("GetDirectDraw", "*ppDirectDraw"),
        ("SetDirectDraw", "pDirectDraw"),
        ("CreateSample", "pSurface *pRect dwFlags *ppSample"),
        ("GetTimePerFrame", "*pFrameTime"),
    ]),
    ("IDirectDrawStreamSample", [
        ("QueryInterface", "*riid *ppvObject"),
        ("AddRef", ""),
        ("Release", ""),
        ("GetMediaStream", "*ppMediaStream"),
        ("GetSampleTimes", "*pStartTime *pEndTime *pCurrentTime"),
        ("SetSampleTimes", "*pStartTime *pEndTime"),
        ("Update", "dwFlags hEvent pfnAPC dwAPCData"),
        ("CompletionStatus", "dwFlags dwMilliseconds"),
        ("GetSurface", "*ppDirectDrawSurface *pRect"),
        ("SetRect", "*pRect"),
    ]),
]


def main():
    out = [";; Generated by tools/gen_com_glue.py. Do not edit.",
           ";; COM glue for the DirectShow multimedia stream objects (WinApi-amstream.c).",
           "", "include llasm.llinc", "include asm-calls.llinc", ""]
    for iface, methods in INTERFACES:
        for name, params in methods:
            p = ["*lpThis"] + params.split()
            out.append("func %s_%s_c %s" % (iface, name, ", ".join(p)))
        out.append("")
    for iface, methods in INTERFACES:
        for name, params in methods:
            n = 1 + len(params.split())
            out.append("proc %s_%s_asm2c public" % (iface, name))
            regs = []
            for i in range(n):
                out.append("        add tmp%d, esp, %d" % (i, 4 * (i + 1)))
                out.append("        load tmp%d, tmp%d, 4" % (i, i))
                regs.append("tmp%d" % i)
            out.append("        call %s_%s_c %s" % (iface, name, ", ".join(regs)))
            out.append("        mov eax, tmp0")
            out.append("        Call_Asm_Return %d" % n)
            out.append("endp")
            out.append("")
    out.append("datasegment amstream_data constant")
    out.append("")
    for iface, methods in INTERFACES:
        out.append("dlabel %sVtbl_asm2c global" % iface)
        for name, _ in methods:
            out.append("daddr %s_%s_asm2c" % (iface, name))
        out.append("")
    out.append("endd")
    print("\n".join(out))


if __name__ == "__main__":
    main()
