# Direct3D 8 interfaces in vtable order. Generated by
# common/native-mac/tools/gen_d3d8.py from d3d8.h. Do not edit.
# The methods are in runtime/d3d8/ (WinApi-d3d8.c and WinApi-d3d8-gen.c).

interface IDirect3D8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    RegisterSoftwareDevice *pInitializeFunction
    GetAdapterCount
    GetAdapterIdentifier Adapter Flags *pIdentifier
    GetAdapterModeCount Adapter
    EnumAdapterModes Adapter Mode *pMode
    GetAdapterDisplayMode Adapter *pMode
    CheckDeviceType Adapter CheckType DisplayFormat BackBufferFormat Windowed
    CheckDeviceFormat Adapter DeviceType AdapterFormat Usage RType CheckFormat
    CheckDeviceMultiSampleType Adapter DeviceType SurfaceFormat Windowed MultiSampleType
    CheckDepthStencilMatch Adapter DeviceType AdapterFormat RenderTargetFormat DepthStencilFormat
    GetDeviceCaps Adapter DeviceType *pCaps
    GetAdapterMonitor Adapter
    CreateDevice Adapter DeviceType *hFocusWindow BehaviorFlags *pPresentationParameters *ppReturnedDeviceInterface

interface IDirect3DVolume8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    GetDevice *ppDevice
    SetPrivateData *refguid *data data_size flags
    GetPrivateData *refguid *pData *pSizeOfData
    FreePrivateData *refguid
    GetContainer *riid *ppContainer
    GetDesc *pDesc
    LockBox *locked_box *box flags
    UnlockBox

interface IDirect3DSwapChain8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    Present *src_rect *dst_rect *dst_window_override *dirty_region
    GetBackBuffer BackBuffer Type *ppBackBuffer

interface IDirect3DSurface8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    GetDevice *ppDevice
    SetPrivateData *refguid *data data_size flags
    GetPrivateData *refguid *pData *pSizeOfData
    FreePrivateData *refguid
    GetContainer *riid *ppContainer
    GetDesc *pDesc
    LockRect *locked_rect *rect flags
    UnlockRect

interface IDirect3DResource8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    GetDevice *ppDevice
    SetPrivateData *refguid *data data_size flags
    GetPrivateData *refguid *pData *pSizeOfData
    FreePrivateData *refguid
    SetPriority PriorityNew
    GetPriority
    PreLoad
    GetType

interface IDirect3DVertexBuffer8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    GetDevice *ppDevice
    SetPrivateData *refguid *data data_size flags
    GetPrivateData *refguid *pData *pSizeOfData
    FreePrivateData *refguid
    SetPriority PriorityNew
    GetPriority
    PreLoad
    GetType
    Lock OffsetToLock SizeToLock *ppbData Flags
    Unlock
    GetDesc *pDesc

interface IDirect3DIndexBuffer8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    GetDevice *ppDevice
    SetPrivateData *refguid *data data_size flags
    GetPrivateData *refguid *pData *pSizeOfData
    FreePrivateData *refguid
    SetPriority PriorityNew
    GetPriority
    PreLoad
    GetType
    Lock OffsetToLock SizeToLock *ppbData Flags
    Unlock
    GetDesc *pDesc

interface IDirect3DBaseTexture8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    GetDevice *ppDevice
    SetPrivateData *refguid *data data_size flags
    GetPrivateData *refguid *pData *pSizeOfData
    FreePrivateData *refguid
    SetPriority PriorityNew
    GetPriority
    PreLoad
    GetType
    SetLOD LODNew
    GetLOD
    GetLevelCount

interface IDirect3DCubeTexture8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    GetDevice *ppDevice
    SetPrivateData *refguid *data data_size flags
    GetPrivateData *refguid *pData *pSizeOfData
    FreePrivateData *refguid
    SetPriority PriorityNew
    GetPriority
    PreLoad
    GetType
    SetLOD LODNew
    GetLOD
    GetLevelCount
    GetLevelDesc Level *pDesc
    GetCubeMapSurface FaceType Level *ppCubeMapSurface
    LockRect face level *locked_rect *rect flags
    UnlockRect FaceType Level
    AddDirtyRect face *dirty_rect

interface IDirect3DTexture8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    GetDevice *ppDevice
    SetPrivateData *refguid *data data_size flags
    GetPrivateData *refguid *pData *pSizeOfData
    FreePrivateData *refguid
    SetPriority PriorityNew
    GetPriority
    PreLoad
    GetType
    SetLOD LODNew
    GetLOD
    GetLevelCount
    GetLevelDesc Level *pDesc
    GetSurfaceLevel Level *ppSurfaceLevel
    LockRect level *locked_rect *rect flags
    UnlockRect Level
    AddDirtyRect *dirty_rect

interface IDirect3DVolumeTexture8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    GetDevice *ppDevice
    SetPrivateData *refguid *data data_size flags
    GetPrivateData *refguid *pData *pSizeOfData
    FreePrivateData *refguid
    SetPriority PriorityNew
    GetPriority
    PreLoad
    GetType
    SetLOD LODNew
    GetLOD
    GetLevelCount
    GetLevelDesc Level *pDesc
    GetVolumeLevel Level *ppVolumeLevel
    LockBox level *locked_box *box flags
    UnlockBox Level
    AddDirtyBox *dirty_box

interface IDirect3DDevice8
    QueryInterface *riid *ppvObject
    AddRef
    Release
    TestCooperativeLevel
    GetAvailableTextureMem
    ResourceManagerDiscardBytes Bytes
    GetDirect3D *ppD3D8
    GetDeviceCaps *pCaps
    GetDisplayMode *pMode
    GetCreationParameters *pParameters
    SetCursorProperties XHotSpot YHotSpot *pCursorBitmap
    SetCursorPosition XScreenSpace YScreenSpace Flags
    ShowCursor bShow
    CreateAdditionalSwapChain *pPresentationParameters *pSwapChain
    Reset *pPresentationParameters
    Present *src_rect *dst_rect *dst_window_override *dirty_region
    GetBackBuffer BackBuffer Type *ppBackBuffer
    GetRasterStatus *pRasterStatus
    SetGammaRamp flags *ramp
    GetGammaRamp *pRamp
    CreateTexture Width Height Levels Usage Format Pool *ppTexture
    CreateVolumeTexture Width Height Depth Levels Usage Format Pool *ppVolumeTexture
    CreateCubeTexture EdgeLength Levels Usage Format Pool *ppCubeTexture
    CreateVertexBuffer Length Usage FVF Pool *ppVertexBuffer
    CreateIndexBuffer Length Usage Format Pool *ppIndexBuffer
    CreateRenderTarget Width Height Format MultiSample Lockable *ppSurface
    CreateDepthStencilSurface Width Height Format MultiSample *ppSurface
    CreateImageSurface Width Height Format *ppSurface
    CopyRects *src_surface *src_rects rect_count *dst_surface *dst_points
    UpdateTexture *pSourceTexture *pDestinationTexture
    GetFrontBuffer *pDestSurface
    SetRenderTarget *pRenderTarget *pNewZStencil
    GetRenderTarget *ppRenderTarget
    GetDepthStencilSurface *ppZStencilSurface
    BeginScene
    EndScene
    Clear rect_count *rects flags color z stencil
    SetTransform state *matrix
    GetTransform State *pMatrix
    MultiplyTransform state *matrix
    SetViewport *viewport
    GetViewport *pViewport
    SetMaterial *material
    GetMaterial *pMaterial
    SetLight index *light
    GetLight Index *pLight
    LightEnable Index Enable
    GetLightEnable Index *pEnable
    SetClipPlane index *plane
    GetClipPlane Index *pPlane
    SetRenderState State Value
    GetRenderState State *pValue
    BeginStateBlock
    EndStateBlock *pToken
    ApplyStateBlock Token
    CaptureStateBlock Token
    DeleteStateBlock Token
    CreateStateBlock Type *pToken
    SetClipStatus *clip_status
    GetClipStatus *pClipStatus
    GetTexture Stage *ppTexture
    SetTexture Stage *pTexture
    GetTextureStageState Stage Type *pValue
    SetTextureStageState Stage Type Value
    ValidateDevice *pNumPasses
    GetInfo DevInfoID *pDevInfoStruct DevInfoStructSize
    SetPaletteEntries palette_idx *entries
    GetPaletteEntries PaletteNumber *pEntries
    SetCurrentTexturePalette PaletteNumber
    GetCurrentTexturePalette *PaletteNumber
    DrawPrimitive PrimitiveType StartVertex PrimitiveCount
    DrawIndexedPrimitive PrimitiveType minIndex NumVertices startIndex primCount
    DrawPrimitiveUP primitive_type primitive_count *data stride
    DrawIndexedPrimitiveUP primitive_type min_vertex_idx vertex_count primitive_count *index_data index_format *data stride
    ProcessVertices SrcStartIndex DestIndex VertexCount *pDestBuffer Flags
    CreateVertexShader *declaration *byte_code *shader usage
    SetVertexShader Handle
    GetVertexShader *pHandle
    DeleteVertexShader Handle
    SetVertexShaderConstant reg_idx *data count
    GetVertexShaderConstant Register *pConstantData ConstantCount
    GetVertexShaderDeclaration Handle *pData *pSizeOfData
    GetVertexShaderFunction Handle *pData *pSizeOfData
    SetStreamSource StreamNumber *pStreamData Stride
    GetStreamSource StreamNumber *ppStreamData *pStride
    SetIndices *pIndexData BaseVertexIndex
    GetIndices *ppIndexData *pBaseVertexIndex
    CreatePixelShader *byte_code *shader
    SetPixelShader Handle
    GetPixelShader *pHandle
    DeletePixelShader Handle
    SetPixelShaderConstant reg_idx *data count
    GetPixelShaderConstant Register *pConstantData ConstantCount
    GetPixelShaderFunction Handle *pData *pSizeOfData
    DrawRectPatch handle *segment_count *patch_info
    DrawTriPatch handle *segment_count *patch_info
    DeletePatch Handle
