#!/usr/bin/env python3
"""Write extern.llinc for the generated llasm code.

The SRW output declares every import as "proc <name> external" with the
name SRW uses (for example "_AIL_startup@0" or "ws2_32.socket"). This file
maps each of these names to the runtime procedure "<clean>_asm2c" (the
"proc ... external" lines in the SRW output then declare them), and
declares the procedures named in external_procedures.sci.

Usage: gen_extern.py <game>.exe external_procedures.sci <GAME_LLASM>.llasm > extern.llinc
"""

import re
import sys

import pefile

WSOCK = {1: "accept", 2: "bind", 3: "closesocket", 4: "connect", 6: "getsockname",
         7: "getsockopt", 8: "htonl", 9: "htons", 10: "inet_addr", 11: "inet_ntoa",
         12: "ioctlsocket", 13: "listen", 14: "ntohl", 15: "ntohs", 16: "recv",
         17: "recvfrom", 18: "select", 19: "send", 20: "sendto", 21: "setsockopt",
         22: "shutdown", 23: "socket", 52: "gethostbyname", 57: "gethostname",
         111: "WSAGetLastError", 115: "WSAStartup", 116: "WSACleanup", 151: "__WSAFDIsSet"}
# OLEAUT32 ordinals (the same names as in SRW_loader.c)
OLEAUT = {2: "SysAllocString", 6: "SysFreeString", 9: "VariantClear", 32: "CreateStdDispatch",
          161: "LoadTypeLib", 200: "GetErrorInfo"}
# Names SRW gives to these ordinals (see SRW_loader.c): most get "ws2_32.".
WSOCK_PLAIN = {"getsockopt", "recv", "recvfrom", "setsockopt"}


# C++ names of MSVCRT and MSVCIRT imports: the runtime procedure names
CXX_NAMES = {
    "??0exception@@QAE@XZ": "exception_ctor",
    "??0exception@@QAE@ABV0@@Z": "exception_copy_ctor",
    "??1exception@@UAE@XZ": "exception_dtor",
    "??1type_info@@UAE@XZ": "type_info_dtor",
    "?terminate@@YAXXZ": "cxx_terminate",
    "?_set_se_translator@@YAP6AXIPAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z": "cxx_set_se_translator",
}


def srw_and_clean(dll, imp):
    if imp.import_by_ordinal and dll.upper() == "OLEAUT32.DLL":
        name = OLEAUT[imp.ordinal]
        return name, name
    if imp.import_by_ordinal:
        name = WSOCK[imp.ordinal]
        srw = name if name in WSOCK_PLAIN else "ws2_32." + name
        return srw, "ws_" + name
    name = imp.name.decode()
    if name in CXX_NAMES:
        return name, CXX_NAMES[name]
    m = re.match(r"_(\w+)@\d+$", name)
    if m:                       # mss32 stdcall decoration: _AIL_startup@0
        return name, m.group(1)
    return name, name


def main():
    pe = pefile.PE(sys.argv[1])
    out = ["; Generated by tools/gen_extern.py. Do not edit.", "", "include native-extra.llinc", ""]
    procs = []
    for d in pe.DIRECTORY_ENTRY_IMPORT:
        dll = d.dll.decode()
        out.append("; " + dll)
        for imp in d.imports:
            srw, clean = srw_and_clean(dll, imp)
            out.append("define %-40s %s_asm2c" % (srw, clean))
            procs.append(clean + "_asm2c")
        out.append("")
    # Imports that the SRW output does not declare (used only through a
    # pointer in data, for example "mov esi, [__imp_X]; call esi").
    declared = set()
    if len(sys.argv) > 3:
        for line in open(sys.argv[3]):
            if line.startswith("proc ") and line.rstrip().endswith(" external"):
                declared.add(line.split()[1])
    out.append("; imports used only through data pointers")
    for d in pe.DIRECTORY_ENTRY_IMPORT:
        for imp in d.imports:
            srw, clean = srw_and_clean(d.dll.decode(), imp)
            if srw not in declared:
                out.append("proc %s_asm2c external" % clean)
    out.append("")
    out.append("; native replacements (external_procedures.sci)")
    declared = set()
    for line in open(sys.argv[2]):
        line = line.split(";")[0].strip()
        if line and line.split(",")[1] not in declared:
            # one native procedure can replace several entry points
            declared.add(line.split(",")[1])
            out.append("proc %s external" % line.split(",")[1])
    out.append("")
    out.append("; stops the program if code that was not translated runs")
    out.append("funcv x86_unsupported_instruction num")
    print("\n".join(out))


if __name__ == "__main__":
    main()
