#!/usr/bin/env python3
"""Generate llasm glue and weak C stubs from runtime/imports.spec.

For each function in the spec (and not already in runtime/llasm/*.llasm):
  - glue-asm.llasm: "proc <name>_asm2c" reads the stdcall parameters from the
    x86 stack, calls <name>_c, puts the result in eax, and pops the params.
  - stubs.c: a weak <name>_c that prints "unimplemented" once and returns 0.
    A real implementation in runtime/*.c replaces it at link time.

Usage: gen_glue.py runtime/imports.spec runtime/llasm build/gen/extern.llinc build/gen
"""

import glob
import os
import re
import sys


def parse_spec(path):
    funcs = []
    for line in open(path):
        line = line.split("#")[0].strip()
        if not line:
            continue
        parts = line.split()
        funcs.append((parts[0], parts[1], parts[2:]))
    return funcs


def main():
    spec, llasm_dir, extern, outdir = sys.argv[1:5]
    funcs = parse_spec(spec)

    have = set()
    for f in glob.glob(os.path.join(llasm_dir, "*.llasm")):
        if os.path.basename(f) == "glue-asm.llasm":
            continue     # the output of an earlier run (common/native-mac/mk/game.mk stages it there)
        for line in open(f):
            m = re.match(r"proc (\w+)_asm2c\b", line)
            if m:
                have.add(m.group(1))

    # Imports the game needs, and the stack bytes of decorated (mss32) names.
    need, stack_bytes = set(), {}
    for line in open(extern):
        m = re.match(r"define\s+(\S+)\s+(\w+)_asm2c", line)
        if m:
            need.add(m.group(2))
            d = re.search(r"@(\d+)$", m.group(1))
            if d:
                stack_bytes[m.group(2)] = int(d.group(1))

    names = {f[1] for f in funcs}
    missing = sorted(need - have - names)
    if missing:
        sys.exit("imports with no glue and no spec entry: " + " ".join(missing))

    asm = ["; Generated by tools/gen_glue.py from runtime/imports.spec. Do not edit.",
           "", "include llasm.llinc", "include asm-calls.llinc", "",
           "; <P>TRACE_IMPORTS=1: each call is logged (glue_trace_import in stubs.c)",
           "funcv glue_trace_import $, index", ""]
    trace_names = []
    stubs = ["/* Generated by tools/gen_glue.py from runtime/imports.spec. Do not edit. */",
             "#include <stdint.h>", "#include <stdio.h>", ""]
    for ret, name, params in funcs:
        if name in have:
            continue
        if ret == "d":
            continue     # data import: a runtime C file defines <name>_asm2c
        if name in stack_bytes and stack_bytes[name] != 4 * len(params):
            sys.exit("%s: spec has %d params, import says %d bytes" % (name, len(params), stack_bytes[name]))
        # Calling convention suffix: "c" cdecl (the caller pops the
        # params), "t" thiscall (the first param is ecx).
        conv = ret[1:] if len(ret) > 1 else ""
        ret = ret[0]
        kind = {"i": "func", "p": "funcp", "v": "funcv", "x": "func", "f": "funcv"}[ret]
        if ret == "x":
            # cdecl with variable arguments: <name>2_c(fixed params..., va)
            decl = ", ".join(params + ["*ap"])
            asm.append("%s %s2_c %s" % (kind, name, decl))
            asm.append("proc %s_asm2c public" % name)
            regs = []
            for i in range(len(params)):
                asm.append("    add tmp%d, esp, %d" % (i, 4 * (i + 1)))
                asm.append("    load tmp%d, tmp%d, 4" % (i, i))
                regs.append("tmp%d" % i)
            n = len(params)
            asm.append("    add tmp%d, esp, %d" % (n, 4 * (n + 1)))
            regs.append("tmp%d" % n)
            asm.append("    call %s2_c %s" % (name, ", ".join(regs)))
            asm.append("    mov eax, tmp0")
            asm.append("    Call_Asm_Return 0")
            asm.append("endp")
            asm.append("")
            stubs.append("__attribute__((weak)) uint32_t %s2_c(void) { fprintf(stderr, \"unimplemented: %s\\n\"); return 0; }" % (name, name))
            continue
        # "f": the result is a double on the x87 stack; the C function gets
        # the CPU first (void <name>_c(_cpu *cpu, ...)) and pushes it.
        decl = ", ".join((["$"] if ret == "f" else []) + params)
        asm.append(("%s %s_c %s" % (kind, name, decl)).rstrip())
        asm.append("proc %s_asm2c public" % name)
        asm.append("    call glue_trace_import $, %d" % len(trace_names))
        trace_names.append(name)
        regs = ["$"] if ret == "f" else []
        stack_params = params[1:] if conv == "t" else params
        if conv == "t":
            asm.append("    mov tmp0, ecx")
            regs.append("tmp0")
        for i in range(len(stack_params)):
            t = len(regs) - (1 if ret == "f" else 0)
            asm.append("    add tmp%d, esp, %d" % (t, 4 * (i + 1)))
            asm.append("    load tmp%d, tmp%d, 4" % (t, t))
            regs.append("tmp%d" % t)
        asm.append(("    call %s_c %s" % (name, ", ".join(regs))).rstrip())
        if ret not in ("v", "f"):
            asm.append("    mov eax, tmp0")
        asm.append("    Call_Asm_Return %d" % (0 if conv == "c" else len(stack_params)))
        asm.append("endp")
        asm.append("")
        rtype = "void" if ret in ("v", "f") else ("void *" if ret == "p" else "uint32_t")
        rval = "" if ret in ("v", "f") else " return 0;"
        stubs.append("__attribute__((weak)) %s %s_c(void) { static int once; if (!once++) fprintf(stderr, \"unimplemented: %s\\n\");%s }"
                     % (rtype, name, name, rval))

    stubs.append("")
    stubs.append("/* <P>TRACE_IMPORTS=1: log each import call (name, guest esp, return address) */")
    stubs.append("#include <stdlib.h>")
    stubs.append("typedef struct { uint32_t eax, ecx, edx, ebx, esp; } glue_regs;")
    stubs.append("static const char *const glue_names[] = {")
    for n in trace_names:
        stubs.append('    "%s",' % n)
    stubs.append("};")
    stubs.append("extern const char *game_getenv(const char *name);")
    stubs.append("extern uint64_t pointer_offset;")
    stubs.append("void glue_trace_import(glue_regs *cpu, uint32_t index)")
    stubs.append("{")
    stubs.append("    static int on = -1;")
    stubs.append("    if (on < 0) on = game_getenv(\"TRACE_IMPORTS\") != NULL;")
    stubs.append("    if (!on) return;")
    stubs.append("    uint32_t ret = *(uint32_t *)(uintptr_t)(pointer_offset + cpu->esp);")
    stubs.append("    fprintf(stderr, \"import %s esp=%08x ret=%08x\\n\", glue_names[index], cpu->esp, ret);")
    stubs.append("}")
    with open(os.path.join(outdir, "glue-asm.llasm"), "w") as fh:
        fh.write("\n".join(asm) + "\n")
    with open(os.path.join(outdir, "stubs.c"), "w") as fh:
        fh.write("\n".join(stubs) + "\n")
    print("glue: %d functions" % sum(1 for f in funcs if f[1] not in have and f[0] != "d"))


if __name__ == "__main__":
    main()
