#!/usr/bin/env python3
"""Make the Direct3D 8 COM glue list and the pass-through methods.

Reads the interfaces of d3d8.h (the native DirectX headers of DXVK) and
writes:

  <out>.com    the interface list for gen_com.py (vtable order). A "*"
               marks a pointer parameter (a host pointer in C).
  <out>-gen.c  C++ functions <Iface>_<Method>_c that call the same method
               of the native DXVK object. Interface parameters are unwrapped
               (the x86 code has a guest wrapper object, runtime/d3d8/
               WinApi-d3d8.c), interface results are wrapped, float
               parameters come as raw dwords. Methods in SPECIAL are written
               by hand in WinApi-d3d8.c (structures with pointers or
               handles, locks, reference counts).

The 32-bit guest layout of all other structures that the methods take
(D3DCAPS8, D3DSURFACE_DESC, D3DMATRIX, RECT, ...) is the same as the
native layout, because they have no pointers.

Usage: gen_d3d8.py <d3d8.h> <out .com> <out -gen.c>
"""

import re
import sys

SPECIAL = {
    ("*", "QueryInterface"), ("*", "Release"),
    ("IDirect3D8", "CreateDevice"),
    ("IDirect3D8", "GetAdapterModeCount"), ("IDirect3D8", "EnumAdapterModes"),
    ("IDirect3DDevice8", "CreateAdditionalSwapChain"), ("IDirect3DDevice8", "Reset"),
    ("IDirect3DDevice8", "Present"), ("IDirect3DDevice8", "GetCreationParameters"),
    ("IDirect3DDevice8", "CopyRects"), ("IDirect3DDevice8", "UpdateTexture"),
    ("IDirect3DSwapChain8", "Present"),
    ("IDirect3DSurface8", "LockRect"), ("IDirect3DSurface8", "UnlockRect"),
    ("IDirect3DSurface8", "GetContainer"), ("IDirect3DVolume8", "GetContainer"),
    ("IDirect3DTexture8", "LockRect"), ("IDirect3DTexture8", "UnlockRect"),
    ("IDirect3DCubeTexture8", "LockRect"), ("IDirect3DCubeTexture8", "UnlockRect"),
    ("IDirect3DVolume8", "LockBox"), ("IDirect3DVolume8", "UnlockBox"),
    ("IDirect3DVolumeTexture8", "LockBox"), ("IDirect3DVolumeTexture8", "UnlockBox"),
    ("IDirect3DVertexBuffer8", "Lock"), ("IDirect3DVertexBuffer8", "Unlock"),
    ("IDirect3DIndexBuffer8", "Lock"), ("IDirect3DIndexBuffer8", "Unlock"),
}


# Methods whose result the layer changes after the native call:
# method name -> C function that gets the guest pointer of the result.
POST = {
    "GetAdapterDisplayMode": "d3d8_fix_display_mode",
    "GetDisplayMode": "d3d8_fix_display_mode",
}


def parse(path):
    text = open(path).read()
    ifaces = []
    for m in re.finditer(r"DECLARE_INTERFACE_\((\w+),\s*(\w+)\)\s*\{(.*?)\};", text, re.S):
        name, body = m.group(1), m.group(3)
        body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
        methods = []
        for mm in re.finditer(r"STDMETHOD(_\(([^,]+),\s*(\w+)\s*\)|\(\s*(\w+)\s*\))\s*\((.*?)\)\s*PURE;", body, re.S):
            if mm.group(2):
                ret, mname = mm.group(2).strip(), mm.group(3)
            else:
                ret, mname = "HRESULT", mm.group(4)
            params = []
            args = " ".join(mm.group(5).split())
            args = re.sub(r"^THIS_?\s*", "", args)
            for p in [a.strip() for a in args.split(",") if a.strip()]:
                pm = re.match(r"(.*?)(\w+)$", p)
                ptype, pname = pm.group(1).strip(), pm.group(2)
                params.append((ptype, pname))
            methods.append((ret, mname, params))
        if len(methods) != body.count("STDMETHOD"):
            sys.exit("%s: %d of %d methods parsed" % (name, len(methods), body.count("STDMETHOD")))
        ifaces.append((name, methods))
    return ifaces


def main():
    header, out_com, out_c = sys.argv[1:4]
    ifaces = parse(header)
    names = {i for i, _ in ifaces}

    com = ["# Direct3D 8 interfaces in vtable order. Generated by",
           "# common/native-mac/tools/gen_d3d8.py from d3d8.h. Do not edit.",
           "# The methods are in runtime/d3d8/ (WinApi-d3d8.c and WinApi-d3d8-gen.c).", ""]
    gen = ["/* Generated by common/native-mac/tools/gen_d3d8.py from d3d8.h. Do not edit.",
           " * Pass-through methods of the Direct3D 8 glue (see WinApi-d3d8.c). */", "",
           '#include "WinApi-d3d8.h"', ""]

    for iface, methods in ifaces:
        com.append("interface %s" % iface)
        for ret, mname, params in methods:
            words = [mname]
            for ptype, pname in params:
                words.append(("*" if ("*" in ptype or ptype in ("REFIID", "REFGUID", "HWND")) else "") + pname)
            com.append("    " + " ".join(words))
        com.append("")

        for ret, mname, params in methods:
            if ("*", mname) in SPECIAL or (iface, mname) in SPECIAL:
                continue
            cparams = ["void *self"]
            pre, args, post = [], [], []
            for ptype, pname in params:
                base = ptype.replace("const ", "").replace("CONST ", "").replace("struct ", "").replace("*", "").strip()
                stars = ptype.count("*")
                if base in names and stars == 1:
                    cparams.append("void *" + pname)
                    args.append("d3d8_unwrap<%s>(%s)" % (base, pname))
                elif base in names and stars == 2:
                    cparams.append("void *" + pname)
                    pre.append("%s *out_%s = nullptr;" % (base, pname))
                    args.append("%s ? &out_%s : nullptr" % (pname, pname))
                    post.append("if (%s) wr32(%s, d3d8_wrap(out_%s));" % (pname, pname, pname))
                elif stars > 0 or base in ("REFIID", "REFGUID"):
                    cparams.append("void *" + pname)
                    args.append("(%s)%s" % (ptype if stars else base, pname))
                elif base == "float":
                    cparams.append("uint32_t " + pname)
                    args.append("d3d8_float(%s)" % pname)
                elif base == "HWND":
                    cparams.append("void *" + pname)
                    args.append("d3d8_hwnd(%s)" % pname)
                else:
                    cparams.append("uint32_t " + pname)
                    args.append("(%s)%s" % (base, pname))
            gen.append("EXTERN_C uint32_t %s_%s_c(%s)" % (iface, mname, ", ".join(cparams)))
            gen.append("{")
            gen.append("    %s *obj = d3d8_native<%s>(self);" % (iface, iface))
            for line in pre:
                gen.append("    " + line)
            call = "obj->%s(%s)" % (mname, ", ".join(args))
            if ret == "void":
                gen.append("    %s;" % call)
                gen.append("    uint32_t r = 0;")
            else:
                gen.append("    uint32_t r = (uint32_t)(uintptr_t)%s;" % call)
            for line in post:
                gen.append("    " + line)
            if mname in POST:
                gen.append("    %s(%s);" % (POST[mname], cparams[-1].split()[-1].lstrip("*")))
            gen.append('    D3D8_TRACE("%s::%s", r);' % (iface, mname))
            pnames = [c.split()[-1].lstrip("*") for c in cparams]
            gen.append('    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   %s(%s) from %%s\\n"%s, guest_caller());' % (
                mname, ", ".join("%p" if c.startswith("void") else "0x%x" for c in cparams),
                "".join(", " + n for n in pnames)))
            gen.append("    return r;")
            gen.append("}")
            gen.append("")

    open(out_com, "w").write("\n".join(com))
    open(out_c, "w").write("\n".join(gen))


if __name__ == "__main__":
    main()
