/* Generated by common/native-mac/tools/gen_d3d8.py from d3d8.h. Do not edit.
 * Pass-through methods of the Direct3D 8 glue (see WinApi-d3d8.c). */

#include "WinApi-d3d8.h"

EXTERN_C uint32_t IDirect3D8_AddRef_c(void *self)
{
    IDirect3D8 *obj = d3d8_native<IDirect3D8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3D8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3D8_RegisterSoftwareDevice_c(void *self, void *pInitializeFunction)
{
    IDirect3D8 *obj = d3d8_native<IDirect3D8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->RegisterSoftwareDevice((void *)pInitializeFunction);
    D3D8_TRACE("IDirect3D8::RegisterSoftwareDevice", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   RegisterSoftwareDevice(%p, %p) from %s\n", self, pInitializeFunction, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3D8_GetAdapterCount_c(void *self)
{
    IDirect3D8 *obj = d3d8_native<IDirect3D8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetAdapterCount();
    D3D8_TRACE("IDirect3D8::GetAdapterCount", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetAdapterCount(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3D8_GetAdapterIdentifier_c(void *self, uint32_t Adapter, uint32_t Flags, void *pIdentifier)
{
    IDirect3D8 *obj = d3d8_native<IDirect3D8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetAdapterIdentifier((UINT)Adapter, (DWORD)Flags, (D3DADAPTER_IDENTIFIER8 *)pIdentifier);
    D3D8_TRACE("IDirect3D8::GetAdapterIdentifier", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetAdapterIdentifier(%p, 0x%x, 0x%x, %p) from %s\n", self, Adapter, Flags, pIdentifier, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3D8_GetAdapterDisplayMode_c(void *self, uint32_t Adapter, void *pMode)
{
    IDirect3D8 *obj = d3d8_native<IDirect3D8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetAdapterDisplayMode((UINT)Adapter, (D3DDISPLAYMODE *)pMode);
    d3d8_fix_display_mode(pMode);
    D3D8_TRACE("IDirect3D8::GetAdapterDisplayMode", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetAdapterDisplayMode(%p, 0x%x, %p) from %s\n", self, Adapter, pMode, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3D8_CheckDeviceType_c(void *self, uint32_t Adapter, uint32_t CheckType, uint32_t DisplayFormat, uint32_t BackBufferFormat, uint32_t Windowed)
{
    IDirect3D8 *obj = d3d8_native<IDirect3D8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->CheckDeviceType((UINT)Adapter, (D3DDEVTYPE)CheckType, (D3DFORMAT)DisplayFormat, (D3DFORMAT)BackBufferFormat, (WINBOOL)Windowed);
    D3D8_TRACE("IDirect3D8::CheckDeviceType", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CheckDeviceType(%p, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x) from %s\n", self, Adapter, CheckType, DisplayFormat, BackBufferFormat, Windowed, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3D8_CheckDeviceFormat_c(void *self, uint32_t Adapter, uint32_t DeviceType, uint32_t AdapterFormat, uint32_t Usage, uint32_t RType, uint32_t CheckFormat)
{
    IDirect3D8 *obj = d3d8_native<IDirect3D8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->CheckDeviceFormat((UINT)Adapter, (D3DDEVTYPE)DeviceType, (D3DFORMAT)AdapterFormat, (DWORD)Usage, (D3DRESOURCETYPE)RType, (D3DFORMAT)CheckFormat);
    D3D8_TRACE("IDirect3D8::CheckDeviceFormat", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CheckDeviceFormat(%p, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x) from %s\n", self, Adapter, DeviceType, AdapterFormat, Usage, RType, CheckFormat, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3D8_CheckDeviceMultiSampleType_c(void *self, uint32_t Adapter, uint32_t DeviceType, uint32_t SurfaceFormat, uint32_t Windowed, uint32_t MultiSampleType)
{
    IDirect3D8 *obj = d3d8_native<IDirect3D8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->CheckDeviceMultiSampleType((UINT)Adapter, (D3DDEVTYPE)DeviceType, (D3DFORMAT)SurfaceFormat, (WINBOOL)Windowed, (D3DMULTISAMPLE_TYPE)MultiSampleType);
    D3D8_TRACE("IDirect3D8::CheckDeviceMultiSampleType", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CheckDeviceMultiSampleType(%p, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x) from %s\n", self, Adapter, DeviceType, SurfaceFormat, Windowed, MultiSampleType, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3D8_CheckDepthStencilMatch_c(void *self, uint32_t Adapter, uint32_t DeviceType, uint32_t AdapterFormat, uint32_t RenderTargetFormat, uint32_t DepthStencilFormat)
{
    IDirect3D8 *obj = d3d8_native<IDirect3D8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->CheckDepthStencilMatch((UINT)Adapter, (D3DDEVTYPE)DeviceType, (D3DFORMAT)AdapterFormat, (D3DFORMAT)RenderTargetFormat, (D3DFORMAT)DepthStencilFormat);
    D3D8_TRACE("IDirect3D8::CheckDepthStencilMatch", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CheckDepthStencilMatch(%p, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x) from %s\n", self, Adapter, DeviceType, AdapterFormat, RenderTargetFormat, DepthStencilFormat, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3D8_GetDeviceCaps_c(void *self, uint32_t Adapter, uint32_t DeviceType, void *pCaps)
{
    IDirect3D8 *obj = d3d8_native<IDirect3D8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDeviceCaps((UINT)Adapter, (D3DDEVTYPE)DeviceType, (D3DCAPS8 *)pCaps);
    D3D8_TRACE("IDirect3D8::GetDeviceCaps", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDeviceCaps(%p, 0x%x, 0x%x, %p) from %s\n", self, Adapter, DeviceType, pCaps, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3D8_GetAdapterMonitor_c(void *self, uint32_t Adapter)
{
    IDirect3D8 *obj = d3d8_native<IDirect3D8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetAdapterMonitor((UINT)Adapter);
    D3D8_TRACE("IDirect3D8::GetAdapterMonitor", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetAdapterMonitor(%p, 0x%x) from %s\n", self, Adapter, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolume8_AddRef_c(void *self)
{
    IDirect3DVolume8 *obj = d3d8_native<IDirect3DVolume8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3DVolume8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolume8_GetDevice_c(void *self, void *ppDevice)
{
    IDirect3DVolume8 *obj = d3d8_native<IDirect3DVolume8>(self);
    IDirect3DDevice8 *out_ppDevice = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDevice(ppDevice ? &out_ppDevice : nullptr);
    if (ppDevice) wr32(ppDevice, d3d8_wrap(out_ppDevice));
    D3D8_TRACE("IDirect3DVolume8::GetDevice", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDevice(%p, %p) from %s\n", self, ppDevice, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolume8_SetPrivateData_c(void *self, void *refguid, void *data, uint32_t data_size, uint32_t flags)
{
    IDirect3DVolume8 *obj = d3d8_native<IDirect3DVolume8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPrivateData((REFGUID)refguid, (const void *)data, (DWORD)data_size, (DWORD)flags);
    D3D8_TRACE("IDirect3DVolume8::SetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPrivateData(%p, %p, %p, 0x%x, 0x%x) from %s\n", self, refguid, data, data_size, flags, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolume8_GetPrivateData_c(void *self, void *refguid, void *pData, void *pSizeOfData)
{
    IDirect3DVolume8 *obj = d3d8_native<IDirect3DVolume8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPrivateData((REFGUID)refguid, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DVolume8::GetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPrivateData(%p, %p, %p, %p) from %s\n", self, refguid, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolume8_FreePrivateData_c(void *self, void *refguid)
{
    IDirect3DVolume8 *obj = d3d8_native<IDirect3DVolume8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->FreePrivateData((REFGUID)refguid);
    D3D8_TRACE("IDirect3DVolume8::FreePrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   FreePrivateData(%p, %p) from %s\n", self, refguid, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolume8_GetDesc_c(void *self, void *pDesc)
{
    IDirect3DVolume8 *obj = d3d8_native<IDirect3DVolume8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDesc((D3DVOLUME_DESC *)pDesc);
    D3D8_TRACE("IDirect3DVolume8::GetDesc", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDesc(%p, %p) from %s\n", self, pDesc, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DSwapChain8_AddRef_c(void *self)
{
    IDirect3DSwapChain8 *obj = d3d8_native<IDirect3DSwapChain8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3DSwapChain8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DSwapChain8_GetBackBuffer_c(void *self, uint32_t BackBuffer, uint32_t Type, void *ppBackBuffer)
{
    IDirect3DSwapChain8 *obj = d3d8_native<IDirect3DSwapChain8>(self);
    IDirect3DSurface8 *out_ppBackBuffer = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetBackBuffer((UINT)BackBuffer, (D3DBACKBUFFER_TYPE)Type, ppBackBuffer ? &out_ppBackBuffer : nullptr);
    if (ppBackBuffer) wr32(ppBackBuffer, d3d8_wrap(out_ppBackBuffer));
    D3D8_TRACE("IDirect3DSwapChain8::GetBackBuffer", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetBackBuffer(%p, 0x%x, 0x%x, %p) from %s\n", self, BackBuffer, Type, ppBackBuffer, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DSurface8_AddRef_c(void *self)
{
    IDirect3DSurface8 *obj = d3d8_native<IDirect3DSurface8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3DSurface8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DSurface8_GetDevice_c(void *self, void *ppDevice)
{
    IDirect3DSurface8 *obj = d3d8_native<IDirect3DSurface8>(self);
    IDirect3DDevice8 *out_ppDevice = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDevice(ppDevice ? &out_ppDevice : nullptr);
    if (ppDevice) wr32(ppDevice, d3d8_wrap(out_ppDevice));
    D3D8_TRACE("IDirect3DSurface8::GetDevice", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDevice(%p, %p) from %s\n", self, ppDevice, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DSurface8_SetPrivateData_c(void *self, void *refguid, void *data, uint32_t data_size, uint32_t flags)
{
    IDirect3DSurface8 *obj = d3d8_native<IDirect3DSurface8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPrivateData((REFGUID)refguid, (const void *)data, (DWORD)data_size, (DWORD)flags);
    D3D8_TRACE("IDirect3DSurface8::SetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPrivateData(%p, %p, %p, 0x%x, 0x%x) from %s\n", self, refguid, data, data_size, flags, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DSurface8_GetPrivateData_c(void *self, void *refguid, void *pData, void *pSizeOfData)
{
    IDirect3DSurface8 *obj = d3d8_native<IDirect3DSurface8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPrivateData((REFGUID)refguid, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DSurface8::GetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPrivateData(%p, %p, %p, %p) from %s\n", self, refguid, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DSurface8_FreePrivateData_c(void *self, void *refguid)
{
    IDirect3DSurface8 *obj = d3d8_native<IDirect3DSurface8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->FreePrivateData((REFGUID)refguid);
    D3D8_TRACE("IDirect3DSurface8::FreePrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   FreePrivateData(%p, %p) from %s\n", self, refguid, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DSurface8_GetDesc_c(void *self, void *pDesc)
{
    IDirect3DSurface8 *obj = d3d8_native<IDirect3DSurface8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDesc((D3DSURFACE_DESC *)pDesc);
    D3D8_TRACE("IDirect3DSurface8::GetDesc", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDesc(%p, %p) from %s\n", self, pDesc, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DResource8_AddRef_c(void *self)
{
    IDirect3DResource8 *obj = d3d8_native<IDirect3DResource8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3DResource8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DResource8_GetDevice_c(void *self, void *ppDevice)
{
    IDirect3DResource8 *obj = d3d8_native<IDirect3DResource8>(self);
    IDirect3DDevice8 *out_ppDevice = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDevice(ppDevice ? &out_ppDevice : nullptr);
    if (ppDevice) wr32(ppDevice, d3d8_wrap(out_ppDevice));
    D3D8_TRACE("IDirect3DResource8::GetDevice", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDevice(%p, %p) from %s\n", self, ppDevice, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DResource8_SetPrivateData_c(void *self, void *refguid, void *data, uint32_t data_size, uint32_t flags)
{
    IDirect3DResource8 *obj = d3d8_native<IDirect3DResource8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPrivateData((REFGUID)refguid, (const void *)data, (DWORD)data_size, (DWORD)flags);
    D3D8_TRACE("IDirect3DResource8::SetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPrivateData(%p, %p, %p, 0x%x, 0x%x) from %s\n", self, refguid, data, data_size, flags, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DResource8_GetPrivateData_c(void *self, void *refguid, void *pData, void *pSizeOfData)
{
    IDirect3DResource8 *obj = d3d8_native<IDirect3DResource8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPrivateData((REFGUID)refguid, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DResource8::GetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPrivateData(%p, %p, %p, %p) from %s\n", self, refguid, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DResource8_FreePrivateData_c(void *self, void *refguid)
{
    IDirect3DResource8 *obj = d3d8_native<IDirect3DResource8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->FreePrivateData((REFGUID)refguid);
    D3D8_TRACE("IDirect3DResource8::FreePrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   FreePrivateData(%p, %p) from %s\n", self, refguid, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DResource8_SetPriority_c(void *self, uint32_t PriorityNew)
{
    IDirect3DResource8 *obj = d3d8_native<IDirect3DResource8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPriority((DWORD)PriorityNew);
    D3D8_TRACE("IDirect3DResource8::SetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPriority(%p, 0x%x) from %s\n", self, PriorityNew, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DResource8_GetPriority_c(void *self)
{
    IDirect3DResource8 *obj = d3d8_native<IDirect3DResource8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPriority();
    D3D8_TRACE("IDirect3DResource8::GetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPriority(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DResource8_PreLoad_c(void *self)
{
    IDirect3DResource8 *obj = d3d8_native<IDirect3DResource8>(self);
    obj->PreLoad();
    uint32_t r = 0;
    D3D8_TRACE("IDirect3DResource8::PreLoad", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   PreLoad(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DResource8_GetType_c(void *self)
{
    IDirect3DResource8 *obj = d3d8_native<IDirect3DResource8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetType();
    D3D8_TRACE("IDirect3DResource8::GetType", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetType(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVertexBuffer8_AddRef_c(void *self)
{
    IDirect3DVertexBuffer8 *obj = d3d8_native<IDirect3DVertexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3DVertexBuffer8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVertexBuffer8_GetDevice_c(void *self, void *ppDevice)
{
    IDirect3DVertexBuffer8 *obj = d3d8_native<IDirect3DVertexBuffer8>(self);
    IDirect3DDevice8 *out_ppDevice = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDevice(ppDevice ? &out_ppDevice : nullptr);
    if (ppDevice) wr32(ppDevice, d3d8_wrap(out_ppDevice));
    D3D8_TRACE("IDirect3DVertexBuffer8::GetDevice", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDevice(%p, %p) from %s\n", self, ppDevice, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVertexBuffer8_SetPrivateData_c(void *self, void *refguid, void *data, uint32_t data_size, uint32_t flags)
{
    IDirect3DVertexBuffer8 *obj = d3d8_native<IDirect3DVertexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPrivateData((REFGUID)refguid, (const void *)data, (DWORD)data_size, (DWORD)flags);
    D3D8_TRACE("IDirect3DVertexBuffer8::SetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPrivateData(%p, %p, %p, 0x%x, 0x%x) from %s\n", self, refguid, data, data_size, flags, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVertexBuffer8_GetPrivateData_c(void *self, void *refguid, void *pData, void *pSizeOfData)
{
    IDirect3DVertexBuffer8 *obj = d3d8_native<IDirect3DVertexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPrivateData((REFGUID)refguid, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DVertexBuffer8::GetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPrivateData(%p, %p, %p, %p) from %s\n", self, refguid, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVertexBuffer8_FreePrivateData_c(void *self, void *refguid)
{
    IDirect3DVertexBuffer8 *obj = d3d8_native<IDirect3DVertexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->FreePrivateData((REFGUID)refguid);
    D3D8_TRACE("IDirect3DVertexBuffer8::FreePrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   FreePrivateData(%p, %p) from %s\n", self, refguid, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVertexBuffer8_SetPriority_c(void *self, uint32_t PriorityNew)
{
    IDirect3DVertexBuffer8 *obj = d3d8_native<IDirect3DVertexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPriority((DWORD)PriorityNew);
    D3D8_TRACE("IDirect3DVertexBuffer8::SetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPriority(%p, 0x%x) from %s\n", self, PriorityNew, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVertexBuffer8_GetPriority_c(void *self)
{
    IDirect3DVertexBuffer8 *obj = d3d8_native<IDirect3DVertexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPriority();
    D3D8_TRACE("IDirect3DVertexBuffer8::GetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPriority(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVertexBuffer8_PreLoad_c(void *self)
{
    IDirect3DVertexBuffer8 *obj = d3d8_native<IDirect3DVertexBuffer8>(self);
    obj->PreLoad();
    uint32_t r = 0;
    D3D8_TRACE("IDirect3DVertexBuffer8::PreLoad", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   PreLoad(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVertexBuffer8_GetType_c(void *self)
{
    IDirect3DVertexBuffer8 *obj = d3d8_native<IDirect3DVertexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetType();
    D3D8_TRACE("IDirect3DVertexBuffer8::GetType", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetType(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVertexBuffer8_GetDesc_c(void *self, void *pDesc)
{
    IDirect3DVertexBuffer8 *obj = d3d8_native<IDirect3DVertexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDesc((D3DVERTEXBUFFER_DESC *)pDesc);
    D3D8_TRACE("IDirect3DVertexBuffer8::GetDesc", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDesc(%p, %p) from %s\n", self, pDesc, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DIndexBuffer8_AddRef_c(void *self)
{
    IDirect3DIndexBuffer8 *obj = d3d8_native<IDirect3DIndexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3DIndexBuffer8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DIndexBuffer8_GetDevice_c(void *self, void *ppDevice)
{
    IDirect3DIndexBuffer8 *obj = d3d8_native<IDirect3DIndexBuffer8>(self);
    IDirect3DDevice8 *out_ppDevice = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDevice(ppDevice ? &out_ppDevice : nullptr);
    if (ppDevice) wr32(ppDevice, d3d8_wrap(out_ppDevice));
    D3D8_TRACE("IDirect3DIndexBuffer8::GetDevice", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDevice(%p, %p) from %s\n", self, ppDevice, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DIndexBuffer8_SetPrivateData_c(void *self, void *refguid, void *data, uint32_t data_size, uint32_t flags)
{
    IDirect3DIndexBuffer8 *obj = d3d8_native<IDirect3DIndexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPrivateData((REFGUID)refguid, (const void *)data, (DWORD)data_size, (DWORD)flags);
    D3D8_TRACE("IDirect3DIndexBuffer8::SetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPrivateData(%p, %p, %p, 0x%x, 0x%x) from %s\n", self, refguid, data, data_size, flags, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DIndexBuffer8_GetPrivateData_c(void *self, void *refguid, void *pData, void *pSizeOfData)
{
    IDirect3DIndexBuffer8 *obj = d3d8_native<IDirect3DIndexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPrivateData((REFGUID)refguid, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DIndexBuffer8::GetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPrivateData(%p, %p, %p, %p) from %s\n", self, refguid, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DIndexBuffer8_FreePrivateData_c(void *self, void *refguid)
{
    IDirect3DIndexBuffer8 *obj = d3d8_native<IDirect3DIndexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->FreePrivateData((REFGUID)refguid);
    D3D8_TRACE("IDirect3DIndexBuffer8::FreePrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   FreePrivateData(%p, %p) from %s\n", self, refguid, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DIndexBuffer8_SetPriority_c(void *self, uint32_t PriorityNew)
{
    IDirect3DIndexBuffer8 *obj = d3d8_native<IDirect3DIndexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPriority((DWORD)PriorityNew);
    D3D8_TRACE("IDirect3DIndexBuffer8::SetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPriority(%p, 0x%x) from %s\n", self, PriorityNew, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DIndexBuffer8_GetPriority_c(void *self)
{
    IDirect3DIndexBuffer8 *obj = d3d8_native<IDirect3DIndexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPriority();
    D3D8_TRACE("IDirect3DIndexBuffer8::GetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPriority(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DIndexBuffer8_PreLoad_c(void *self)
{
    IDirect3DIndexBuffer8 *obj = d3d8_native<IDirect3DIndexBuffer8>(self);
    obj->PreLoad();
    uint32_t r = 0;
    D3D8_TRACE("IDirect3DIndexBuffer8::PreLoad", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   PreLoad(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DIndexBuffer8_GetType_c(void *self)
{
    IDirect3DIndexBuffer8 *obj = d3d8_native<IDirect3DIndexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetType();
    D3D8_TRACE("IDirect3DIndexBuffer8::GetType", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetType(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DIndexBuffer8_GetDesc_c(void *self, void *pDesc)
{
    IDirect3DIndexBuffer8 *obj = d3d8_native<IDirect3DIndexBuffer8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDesc((D3DINDEXBUFFER_DESC *)pDesc);
    D3D8_TRACE("IDirect3DIndexBuffer8::GetDesc", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDesc(%p, %p) from %s\n", self, pDesc, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_AddRef_c(void *self)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3DBaseTexture8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_GetDevice_c(void *self, void *ppDevice)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    IDirect3DDevice8 *out_ppDevice = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDevice(ppDevice ? &out_ppDevice : nullptr);
    if (ppDevice) wr32(ppDevice, d3d8_wrap(out_ppDevice));
    D3D8_TRACE("IDirect3DBaseTexture8::GetDevice", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDevice(%p, %p) from %s\n", self, ppDevice, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_SetPrivateData_c(void *self, void *refguid, void *data, uint32_t data_size, uint32_t flags)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPrivateData((REFGUID)refguid, (const void *)data, (DWORD)data_size, (DWORD)flags);
    D3D8_TRACE("IDirect3DBaseTexture8::SetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPrivateData(%p, %p, %p, 0x%x, 0x%x) from %s\n", self, refguid, data, data_size, flags, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_GetPrivateData_c(void *self, void *refguid, void *pData, void *pSizeOfData)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPrivateData((REFGUID)refguid, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DBaseTexture8::GetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPrivateData(%p, %p, %p, %p) from %s\n", self, refguid, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_FreePrivateData_c(void *self, void *refguid)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->FreePrivateData((REFGUID)refguid);
    D3D8_TRACE("IDirect3DBaseTexture8::FreePrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   FreePrivateData(%p, %p) from %s\n", self, refguid, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_SetPriority_c(void *self, uint32_t PriorityNew)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPriority((DWORD)PriorityNew);
    D3D8_TRACE("IDirect3DBaseTexture8::SetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPriority(%p, 0x%x) from %s\n", self, PriorityNew, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_GetPriority_c(void *self)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPriority();
    D3D8_TRACE("IDirect3DBaseTexture8::GetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPriority(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_PreLoad_c(void *self)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    obj->PreLoad();
    uint32_t r = 0;
    D3D8_TRACE("IDirect3DBaseTexture8::PreLoad", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   PreLoad(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_GetType_c(void *self)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetType();
    D3D8_TRACE("IDirect3DBaseTexture8::GetType", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetType(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_SetLOD_c(void *self, uint32_t LODNew)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetLOD((DWORD)LODNew);
    D3D8_TRACE("IDirect3DBaseTexture8::SetLOD", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetLOD(%p, 0x%x) from %s\n", self, LODNew, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_GetLOD_c(void *self)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLOD();
    D3D8_TRACE("IDirect3DBaseTexture8::GetLOD", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLOD(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DBaseTexture8_GetLevelCount_c(void *self)
{
    IDirect3DBaseTexture8 *obj = d3d8_native<IDirect3DBaseTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLevelCount();
    D3D8_TRACE("IDirect3DBaseTexture8::GetLevelCount", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLevelCount(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_AddRef_c(void *self)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3DCubeTexture8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_GetDevice_c(void *self, void *ppDevice)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    IDirect3DDevice8 *out_ppDevice = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDevice(ppDevice ? &out_ppDevice : nullptr);
    if (ppDevice) wr32(ppDevice, d3d8_wrap(out_ppDevice));
    D3D8_TRACE("IDirect3DCubeTexture8::GetDevice", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDevice(%p, %p) from %s\n", self, ppDevice, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_SetPrivateData_c(void *self, void *refguid, void *data, uint32_t data_size, uint32_t flags)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPrivateData((REFGUID)refguid, (const void *)data, (DWORD)data_size, (DWORD)flags);
    D3D8_TRACE("IDirect3DCubeTexture8::SetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPrivateData(%p, %p, %p, 0x%x, 0x%x) from %s\n", self, refguid, data, data_size, flags, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_GetPrivateData_c(void *self, void *refguid, void *pData, void *pSizeOfData)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPrivateData((REFGUID)refguid, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DCubeTexture8::GetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPrivateData(%p, %p, %p, %p) from %s\n", self, refguid, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_FreePrivateData_c(void *self, void *refguid)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->FreePrivateData((REFGUID)refguid);
    D3D8_TRACE("IDirect3DCubeTexture8::FreePrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   FreePrivateData(%p, %p) from %s\n", self, refguid, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_SetPriority_c(void *self, uint32_t PriorityNew)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPriority((DWORD)PriorityNew);
    D3D8_TRACE("IDirect3DCubeTexture8::SetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPriority(%p, 0x%x) from %s\n", self, PriorityNew, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_GetPriority_c(void *self)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPriority();
    D3D8_TRACE("IDirect3DCubeTexture8::GetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPriority(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_PreLoad_c(void *self)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    obj->PreLoad();
    uint32_t r = 0;
    D3D8_TRACE("IDirect3DCubeTexture8::PreLoad", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   PreLoad(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_GetType_c(void *self)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetType();
    D3D8_TRACE("IDirect3DCubeTexture8::GetType", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetType(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_SetLOD_c(void *self, uint32_t LODNew)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetLOD((DWORD)LODNew);
    D3D8_TRACE("IDirect3DCubeTexture8::SetLOD", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetLOD(%p, 0x%x) from %s\n", self, LODNew, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_GetLOD_c(void *self)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLOD();
    D3D8_TRACE("IDirect3DCubeTexture8::GetLOD", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLOD(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_GetLevelCount_c(void *self)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLevelCount();
    D3D8_TRACE("IDirect3DCubeTexture8::GetLevelCount", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLevelCount(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_GetLevelDesc_c(void *self, uint32_t Level, void *pDesc)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLevelDesc((UINT)Level, (D3DSURFACE_DESC *)pDesc);
    D3D8_TRACE("IDirect3DCubeTexture8::GetLevelDesc", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLevelDesc(%p, 0x%x, %p) from %s\n", self, Level, pDesc, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_GetCubeMapSurface_c(void *self, uint32_t FaceType, uint32_t Level, void *ppCubeMapSurface)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    IDirect3DSurface8 *out_ppCubeMapSurface = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetCubeMapSurface((D3DCUBEMAP_FACES)FaceType, (UINT)Level, ppCubeMapSurface ? &out_ppCubeMapSurface : nullptr);
    if (ppCubeMapSurface) wr32(ppCubeMapSurface, d3d8_wrap(out_ppCubeMapSurface));
    D3D8_TRACE("IDirect3DCubeTexture8::GetCubeMapSurface", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetCubeMapSurface(%p, 0x%x, 0x%x, %p) from %s\n", self, FaceType, Level, ppCubeMapSurface, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DCubeTexture8_AddDirtyRect_c(void *self, uint32_t face, void *dirty_rect)
{
    IDirect3DCubeTexture8 *obj = d3d8_native<IDirect3DCubeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddDirtyRect((D3DCUBEMAP_FACES)face, (const RECT *)dirty_rect);
    D3D8_TRACE("IDirect3DCubeTexture8::AddDirtyRect", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddDirtyRect(%p, 0x%x, %p) from %s\n", self, face, dirty_rect, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_AddRef_c(void *self)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3DTexture8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_GetDevice_c(void *self, void *ppDevice)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    IDirect3DDevice8 *out_ppDevice = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDevice(ppDevice ? &out_ppDevice : nullptr);
    if (ppDevice) wr32(ppDevice, d3d8_wrap(out_ppDevice));
    D3D8_TRACE("IDirect3DTexture8::GetDevice", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDevice(%p, %p) from %s\n", self, ppDevice, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_SetPrivateData_c(void *self, void *refguid, void *data, uint32_t data_size, uint32_t flags)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPrivateData((REFGUID)refguid, (const void *)data, (DWORD)data_size, (DWORD)flags);
    D3D8_TRACE("IDirect3DTexture8::SetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPrivateData(%p, %p, %p, 0x%x, 0x%x) from %s\n", self, refguid, data, data_size, flags, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_GetPrivateData_c(void *self, void *refguid, void *pData, void *pSizeOfData)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPrivateData((REFGUID)refguid, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DTexture8::GetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPrivateData(%p, %p, %p, %p) from %s\n", self, refguid, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_FreePrivateData_c(void *self, void *refguid)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->FreePrivateData((REFGUID)refguid);
    D3D8_TRACE("IDirect3DTexture8::FreePrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   FreePrivateData(%p, %p) from %s\n", self, refguid, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_SetPriority_c(void *self, uint32_t PriorityNew)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPriority((DWORD)PriorityNew);
    D3D8_TRACE("IDirect3DTexture8::SetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPriority(%p, 0x%x) from %s\n", self, PriorityNew, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_GetPriority_c(void *self)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPriority();
    D3D8_TRACE("IDirect3DTexture8::GetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPriority(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_PreLoad_c(void *self)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    obj->PreLoad();
    uint32_t r = 0;
    D3D8_TRACE("IDirect3DTexture8::PreLoad", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   PreLoad(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_GetType_c(void *self)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetType();
    D3D8_TRACE("IDirect3DTexture8::GetType", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetType(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_SetLOD_c(void *self, uint32_t LODNew)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetLOD((DWORD)LODNew);
    D3D8_TRACE("IDirect3DTexture8::SetLOD", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetLOD(%p, 0x%x) from %s\n", self, LODNew, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_GetLOD_c(void *self)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLOD();
    D3D8_TRACE("IDirect3DTexture8::GetLOD", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLOD(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_GetLevelCount_c(void *self)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLevelCount();
    D3D8_TRACE("IDirect3DTexture8::GetLevelCount", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLevelCount(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_GetLevelDesc_c(void *self, uint32_t Level, void *pDesc)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLevelDesc((UINT)Level, (D3DSURFACE_DESC *)pDesc);
    D3D8_TRACE("IDirect3DTexture8::GetLevelDesc", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLevelDesc(%p, 0x%x, %p) from %s\n", self, Level, pDesc, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_GetSurfaceLevel_c(void *self, uint32_t Level, void *ppSurfaceLevel)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    IDirect3DSurface8 *out_ppSurfaceLevel = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetSurfaceLevel((UINT)Level, ppSurfaceLevel ? &out_ppSurfaceLevel : nullptr);
    if (ppSurfaceLevel) wr32(ppSurfaceLevel, d3d8_wrap(out_ppSurfaceLevel));
    D3D8_TRACE("IDirect3DTexture8::GetSurfaceLevel", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetSurfaceLevel(%p, 0x%x, %p) from %s\n", self, Level, ppSurfaceLevel, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DTexture8_AddDirtyRect_c(void *self, void *dirty_rect)
{
    IDirect3DTexture8 *obj = d3d8_native<IDirect3DTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddDirtyRect((const RECT *)dirty_rect);
    D3D8_TRACE("IDirect3DTexture8::AddDirtyRect", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddDirtyRect(%p, %p) from %s\n", self, dirty_rect, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_AddRef_c(void *self)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3DVolumeTexture8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_GetDevice_c(void *self, void *ppDevice)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    IDirect3DDevice8 *out_ppDevice = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDevice(ppDevice ? &out_ppDevice : nullptr);
    if (ppDevice) wr32(ppDevice, d3d8_wrap(out_ppDevice));
    D3D8_TRACE("IDirect3DVolumeTexture8::GetDevice", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDevice(%p, %p) from %s\n", self, ppDevice, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_SetPrivateData_c(void *self, void *refguid, void *data, uint32_t data_size, uint32_t flags)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPrivateData((REFGUID)refguid, (const void *)data, (DWORD)data_size, (DWORD)flags);
    D3D8_TRACE("IDirect3DVolumeTexture8::SetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPrivateData(%p, %p, %p, 0x%x, 0x%x) from %s\n", self, refguid, data, data_size, flags, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_GetPrivateData_c(void *self, void *refguid, void *pData, void *pSizeOfData)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPrivateData((REFGUID)refguid, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DVolumeTexture8::GetPrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPrivateData(%p, %p, %p, %p) from %s\n", self, refguid, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_FreePrivateData_c(void *self, void *refguid)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->FreePrivateData((REFGUID)refguid);
    D3D8_TRACE("IDirect3DVolumeTexture8::FreePrivateData", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   FreePrivateData(%p, %p) from %s\n", self, refguid, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_SetPriority_c(void *self, uint32_t PriorityNew)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPriority((DWORD)PriorityNew);
    D3D8_TRACE("IDirect3DVolumeTexture8::SetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPriority(%p, 0x%x) from %s\n", self, PriorityNew, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_GetPriority_c(void *self)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPriority();
    D3D8_TRACE("IDirect3DVolumeTexture8::GetPriority", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPriority(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_PreLoad_c(void *self)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    obj->PreLoad();
    uint32_t r = 0;
    D3D8_TRACE("IDirect3DVolumeTexture8::PreLoad", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   PreLoad(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_GetType_c(void *self)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetType();
    D3D8_TRACE("IDirect3DVolumeTexture8::GetType", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetType(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_SetLOD_c(void *self, uint32_t LODNew)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetLOD((DWORD)LODNew);
    D3D8_TRACE("IDirect3DVolumeTexture8::SetLOD", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetLOD(%p, 0x%x) from %s\n", self, LODNew, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_GetLOD_c(void *self)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLOD();
    D3D8_TRACE("IDirect3DVolumeTexture8::GetLOD", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLOD(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_GetLevelCount_c(void *self)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLevelCount();
    D3D8_TRACE("IDirect3DVolumeTexture8::GetLevelCount", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLevelCount(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_GetLevelDesc_c(void *self, uint32_t Level, void *pDesc)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLevelDesc((UINT)Level, (D3DVOLUME_DESC *)pDesc);
    D3D8_TRACE("IDirect3DVolumeTexture8::GetLevelDesc", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLevelDesc(%p, 0x%x, %p) from %s\n", self, Level, pDesc, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_GetVolumeLevel_c(void *self, uint32_t Level, void *ppVolumeLevel)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    IDirect3DVolume8 *out_ppVolumeLevel = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetVolumeLevel((UINT)Level, ppVolumeLevel ? &out_ppVolumeLevel : nullptr);
    if (ppVolumeLevel) wr32(ppVolumeLevel, d3d8_wrap(out_ppVolumeLevel));
    D3D8_TRACE("IDirect3DVolumeTexture8::GetVolumeLevel", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetVolumeLevel(%p, 0x%x, %p) from %s\n", self, Level, ppVolumeLevel, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DVolumeTexture8_AddDirtyBox_c(void *self, void *dirty_box)
{
    IDirect3DVolumeTexture8 *obj = d3d8_native<IDirect3DVolumeTexture8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddDirtyBox((const D3DBOX *)dirty_box);
    D3D8_TRACE("IDirect3DVolumeTexture8::AddDirtyBox", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddDirtyBox(%p, %p) from %s\n", self, dirty_box, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_AddRef_c(void *self)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->AddRef();
    D3D8_TRACE("IDirect3DDevice8::AddRef", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   AddRef(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_TestCooperativeLevel_c(void *self)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->TestCooperativeLevel();
    D3D8_TRACE("IDirect3DDevice8::TestCooperativeLevel", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   TestCooperativeLevel(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetAvailableTextureMem_c(void *self)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetAvailableTextureMem();
    D3D8_TRACE("IDirect3DDevice8::GetAvailableTextureMem", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetAvailableTextureMem(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_ResourceManagerDiscardBytes_c(void *self, uint32_t Bytes)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->ResourceManagerDiscardBytes((DWORD)Bytes);
    D3D8_TRACE("IDirect3DDevice8::ResourceManagerDiscardBytes", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   ResourceManagerDiscardBytes(%p, 0x%x) from %s\n", self, Bytes, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetDirect3D_c(void *self, void *ppD3D8)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3D8 *out_ppD3D8 = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDirect3D(ppD3D8 ? &out_ppD3D8 : nullptr);
    if (ppD3D8) wr32(ppD3D8, d3d8_wrap(out_ppD3D8));
    D3D8_TRACE("IDirect3DDevice8::GetDirect3D", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDirect3D(%p, %p) from %s\n", self, ppD3D8, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetDeviceCaps_c(void *self, void *pCaps)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDeviceCaps((D3DCAPS8 *)pCaps);
    D3D8_TRACE("IDirect3DDevice8::GetDeviceCaps", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDeviceCaps(%p, %p) from %s\n", self, pCaps, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetDisplayMode_c(void *self, void *pMode)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDisplayMode((D3DDISPLAYMODE *)pMode);
    d3d8_fix_display_mode(pMode);
    D3D8_TRACE("IDirect3DDevice8::GetDisplayMode", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDisplayMode(%p, %p) from %s\n", self, pMode, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetCursorProperties_c(void *self, uint32_t XHotSpot, uint32_t YHotSpot, void *pCursorBitmap)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetCursorProperties((UINT)XHotSpot, (UINT)YHotSpot, d3d8_unwrap<IDirect3DSurface8>(pCursorBitmap));
    D3D8_TRACE("IDirect3DDevice8::SetCursorProperties", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetCursorProperties(%p, 0x%x, 0x%x, %p) from %s\n", self, XHotSpot, YHotSpot, pCursorBitmap, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetCursorPosition_c(void *self, uint32_t XScreenSpace, uint32_t YScreenSpace, uint32_t Flags)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    obj->SetCursorPosition((UINT)XScreenSpace, (UINT)YScreenSpace, (DWORD)Flags);
    uint32_t r = 0;
    D3D8_TRACE("IDirect3DDevice8::SetCursorPosition", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetCursorPosition(%p, 0x%x, 0x%x, 0x%x) from %s\n", self, XScreenSpace, YScreenSpace, Flags, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_ShowCursor_c(void *self, uint32_t bShow)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->ShowCursor((WINBOOL)bShow);
    D3D8_TRACE("IDirect3DDevice8::ShowCursor", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   ShowCursor(%p, 0x%x) from %s\n", self, bShow, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetBackBuffer_c(void *self, uint32_t BackBuffer, uint32_t Type, void *ppBackBuffer)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DSurface8 *out_ppBackBuffer = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetBackBuffer((UINT)BackBuffer, (D3DBACKBUFFER_TYPE)Type, ppBackBuffer ? &out_ppBackBuffer : nullptr);
    if (ppBackBuffer) wr32(ppBackBuffer, d3d8_wrap(out_ppBackBuffer));
    D3D8_TRACE("IDirect3DDevice8::GetBackBuffer", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetBackBuffer(%p, 0x%x, 0x%x, %p) from %s\n", self, BackBuffer, Type, ppBackBuffer, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetRasterStatus_c(void *self, void *pRasterStatus)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetRasterStatus((D3DRASTER_STATUS *)pRasterStatus);
    D3D8_TRACE("IDirect3DDevice8::GetRasterStatus", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetRasterStatus(%p, %p) from %s\n", self, pRasterStatus, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetGammaRamp_c(void *self, uint32_t flags, void *ramp)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    obj->SetGammaRamp((DWORD)flags, (const D3DGAMMARAMP *)ramp);
    uint32_t r = 0;
    D3D8_TRACE("IDirect3DDevice8::SetGammaRamp", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetGammaRamp(%p, 0x%x, %p) from %s\n", self, flags, ramp, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetGammaRamp_c(void *self, void *pRamp)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    obj->GetGammaRamp((D3DGAMMARAMP *)pRamp);
    uint32_t r = 0;
    D3D8_TRACE("IDirect3DDevice8::GetGammaRamp", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetGammaRamp(%p, %p) from %s\n", self, pRamp, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CreateTexture_c(void *self, uint32_t Width, uint32_t Height, uint32_t Levels, uint32_t Usage, uint32_t Format, uint32_t Pool, void *ppTexture)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DTexture8 *out_ppTexture = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->CreateTexture((UINT)Width, (UINT)Height, (UINT)Levels, (DWORD)Usage, (D3DFORMAT)Format, (D3DPOOL)Pool, ppTexture ? &out_ppTexture : nullptr);
    if (ppTexture) wr32(ppTexture, d3d8_wrap(out_ppTexture));
    D3D8_TRACE("IDirect3DDevice8::CreateTexture", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CreateTexture(%p, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, %p) from %s\n", self, Width, Height, Levels, Usage, Format, Pool, ppTexture, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CreateVolumeTexture_c(void *self, uint32_t Width, uint32_t Height, uint32_t Depth, uint32_t Levels, uint32_t Usage, uint32_t Format, uint32_t Pool, void *ppVolumeTexture)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DVolumeTexture8 *out_ppVolumeTexture = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->CreateVolumeTexture((UINT)Width, (UINT)Height, (UINT)Depth, (UINT)Levels, (DWORD)Usage, (D3DFORMAT)Format, (D3DPOOL)Pool, ppVolumeTexture ? &out_ppVolumeTexture : nullptr);
    if (ppVolumeTexture) wr32(ppVolumeTexture, d3d8_wrap(out_ppVolumeTexture));
    D3D8_TRACE("IDirect3DDevice8::CreateVolumeTexture", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CreateVolumeTexture(%p, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, %p) from %s\n", self, Width, Height, Depth, Levels, Usage, Format, Pool, ppVolumeTexture, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CreateCubeTexture_c(void *self, uint32_t EdgeLength, uint32_t Levels, uint32_t Usage, uint32_t Format, uint32_t Pool, void *ppCubeTexture)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DCubeTexture8 *out_ppCubeTexture = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->CreateCubeTexture((UINT)EdgeLength, (UINT)Levels, (DWORD)Usage, (D3DFORMAT)Format, (D3DPOOL)Pool, ppCubeTexture ? &out_ppCubeTexture : nullptr);
    if (ppCubeTexture) wr32(ppCubeTexture, d3d8_wrap(out_ppCubeTexture));
    D3D8_TRACE("IDirect3DDevice8::CreateCubeTexture", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CreateCubeTexture(%p, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, %p) from %s\n", self, EdgeLength, Levels, Usage, Format, Pool, ppCubeTexture, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CreateVertexBuffer_c(void *self, uint32_t Length, uint32_t Usage, uint32_t FVF, uint32_t Pool, void *ppVertexBuffer)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DVertexBuffer8 *out_ppVertexBuffer = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->CreateVertexBuffer((UINT)Length, (DWORD)Usage, (DWORD)FVF, (D3DPOOL)Pool, ppVertexBuffer ? &out_ppVertexBuffer : nullptr);
    if (ppVertexBuffer) wr32(ppVertexBuffer, d3d8_wrap(out_ppVertexBuffer));
    D3D8_TRACE("IDirect3DDevice8::CreateVertexBuffer", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CreateVertexBuffer(%p, 0x%x, 0x%x, 0x%x, 0x%x, %p) from %s\n", self, Length, Usage, FVF, Pool, ppVertexBuffer, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CreateIndexBuffer_c(void *self, uint32_t Length, uint32_t Usage, uint32_t Format, uint32_t Pool, void *ppIndexBuffer)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DIndexBuffer8 *out_ppIndexBuffer = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->CreateIndexBuffer((UINT)Length, (DWORD)Usage, (D3DFORMAT)Format, (D3DPOOL)Pool, ppIndexBuffer ? &out_ppIndexBuffer : nullptr);
    if (ppIndexBuffer) wr32(ppIndexBuffer, d3d8_wrap(out_ppIndexBuffer));
    D3D8_TRACE("IDirect3DDevice8::CreateIndexBuffer", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CreateIndexBuffer(%p, 0x%x, 0x%x, 0x%x, 0x%x, %p) from %s\n", self, Length, Usage, Format, Pool, ppIndexBuffer, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CreateRenderTarget_c(void *self, uint32_t Width, uint32_t Height, uint32_t Format, uint32_t MultiSample, uint32_t Lockable, void *ppSurface)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DSurface8 *out_ppSurface = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->CreateRenderTarget((UINT)Width, (UINT)Height, (D3DFORMAT)Format, (D3DMULTISAMPLE_TYPE)MultiSample, (WINBOOL)Lockable, ppSurface ? &out_ppSurface : nullptr);
    if (ppSurface) wr32(ppSurface, d3d8_wrap(out_ppSurface));
    D3D8_TRACE("IDirect3DDevice8::CreateRenderTarget", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CreateRenderTarget(%p, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, %p) from %s\n", self, Width, Height, Format, MultiSample, Lockable, ppSurface, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CreateDepthStencilSurface_c(void *self, uint32_t Width, uint32_t Height, uint32_t Format, uint32_t MultiSample, void *ppSurface)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DSurface8 *out_ppSurface = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->CreateDepthStencilSurface((UINT)Width, (UINT)Height, (D3DFORMAT)Format, (D3DMULTISAMPLE_TYPE)MultiSample, ppSurface ? &out_ppSurface : nullptr);
    if (ppSurface) wr32(ppSurface, d3d8_wrap(out_ppSurface));
    D3D8_TRACE("IDirect3DDevice8::CreateDepthStencilSurface", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CreateDepthStencilSurface(%p, 0x%x, 0x%x, 0x%x, 0x%x, %p) from %s\n", self, Width, Height, Format, MultiSample, ppSurface, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CreateImageSurface_c(void *self, uint32_t Width, uint32_t Height, uint32_t Format, void *ppSurface)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DSurface8 *out_ppSurface = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->CreateImageSurface((UINT)Width, (UINT)Height, (D3DFORMAT)Format, ppSurface ? &out_ppSurface : nullptr);
    if (ppSurface) wr32(ppSurface, d3d8_wrap(out_ppSurface));
    D3D8_TRACE("IDirect3DDevice8::CreateImageSurface", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CreateImageSurface(%p, 0x%x, 0x%x, 0x%x, %p) from %s\n", self, Width, Height, Format, ppSurface, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetFrontBuffer_c(void *self, void *pDestSurface)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetFrontBuffer(d3d8_unwrap<IDirect3DSurface8>(pDestSurface));
    D3D8_TRACE("IDirect3DDevice8::GetFrontBuffer", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetFrontBuffer(%p, %p) from %s\n", self, pDestSurface, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetRenderTarget_c(void *self, void *pRenderTarget, void *pNewZStencil)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetRenderTarget(d3d8_unwrap<IDirect3DSurface8>(pRenderTarget), d3d8_unwrap<IDirect3DSurface8>(pNewZStencil));
    D3D8_TRACE("IDirect3DDevice8::SetRenderTarget", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetRenderTarget(%p, %p, %p) from %s\n", self, pRenderTarget, pNewZStencil, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetRenderTarget_c(void *self, void *ppRenderTarget)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DSurface8 *out_ppRenderTarget = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetRenderTarget(ppRenderTarget ? &out_ppRenderTarget : nullptr);
    if (ppRenderTarget) wr32(ppRenderTarget, d3d8_wrap(out_ppRenderTarget));
    D3D8_TRACE("IDirect3DDevice8::GetRenderTarget", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetRenderTarget(%p, %p) from %s\n", self, ppRenderTarget, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetDepthStencilSurface_c(void *self, void *ppZStencilSurface)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DSurface8 *out_ppZStencilSurface = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetDepthStencilSurface(ppZStencilSurface ? &out_ppZStencilSurface : nullptr);
    if (ppZStencilSurface) wr32(ppZStencilSurface, d3d8_wrap(out_ppZStencilSurface));
    D3D8_TRACE("IDirect3DDevice8::GetDepthStencilSurface", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetDepthStencilSurface(%p, %p) from %s\n", self, ppZStencilSurface, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_BeginScene_c(void *self)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->BeginScene();
    D3D8_TRACE("IDirect3DDevice8::BeginScene", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   BeginScene(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_EndScene_c(void *self)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->EndScene();
    D3D8_TRACE("IDirect3DDevice8::EndScene", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   EndScene(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_Clear_c(void *self, uint32_t rect_count, void *rects, uint32_t flags, uint32_t color, uint32_t z, uint32_t stencil)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->Clear((DWORD)rect_count, (const D3DRECT *)rects, (DWORD)flags, (D3DCOLOR)color, d3d8_float(z), (DWORD)stencil);
    D3D8_TRACE("IDirect3DDevice8::Clear", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   Clear(%p, 0x%x, %p, 0x%x, 0x%x, 0x%x, 0x%x) from %s\n", self, rect_count, rects, flags, color, z, stencil, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetTransform_c(void *self, uint32_t state, void *matrix)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetTransform((D3DTRANSFORMSTATETYPE)state, (const D3DMATRIX *)matrix);
    D3D8_TRACE("IDirect3DDevice8::SetTransform", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetTransform(%p, 0x%x, %p) from %s\n", self, state, matrix, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetTransform_c(void *self, uint32_t State, void *pMatrix)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetTransform((D3DTRANSFORMSTATETYPE)State, (D3DMATRIX *)pMatrix);
    D3D8_TRACE("IDirect3DDevice8::GetTransform", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetTransform(%p, 0x%x, %p) from %s\n", self, State, pMatrix, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_MultiplyTransform_c(void *self, uint32_t state, void *matrix)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->MultiplyTransform((D3DTRANSFORMSTATETYPE)state, (const D3DMATRIX *)matrix);
    D3D8_TRACE("IDirect3DDevice8::MultiplyTransform", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   MultiplyTransform(%p, 0x%x, %p) from %s\n", self, state, matrix, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetViewport_c(void *self, void *viewport)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetViewport((const D3DVIEWPORT8 *)viewport);
    D3D8_TRACE("IDirect3DDevice8::SetViewport", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetViewport(%p, %p) from %s\n", self, viewport, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetViewport_c(void *self, void *pViewport)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetViewport((D3DVIEWPORT8 *)pViewport);
    D3D8_TRACE("IDirect3DDevice8::GetViewport", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetViewport(%p, %p) from %s\n", self, pViewport, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetMaterial_c(void *self, void *material)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetMaterial((const D3DMATERIAL8 *)material);
    D3D8_TRACE("IDirect3DDevice8::SetMaterial", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetMaterial(%p, %p) from %s\n", self, material, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetMaterial_c(void *self, void *pMaterial)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetMaterial((D3DMATERIAL8 *)pMaterial);
    D3D8_TRACE("IDirect3DDevice8::GetMaterial", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetMaterial(%p, %p) from %s\n", self, pMaterial, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetLight_c(void *self, uint32_t index, void *light)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetLight((DWORD)index, (const D3DLIGHT8 *)light);
    D3D8_TRACE("IDirect3DDevice8::SetLight", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetLight(%p, 0x%x, %p) from %s\n", self, index, light, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetLight_c(void *self, uint32_t Index, void *pLight)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLight((DWORD)Index, (D3DLIGHT8 *)pLight);
    D3D8_TRACE("IDirect3DDevice8::GetLight", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLight(%p, 0x%x, %p) from %s\n", self, Index, pLight, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_LightEnable_c(void *self, uint32_t Index, uint32_t Enable)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->LightEnable((DWORD)Index, (WINBOOL)Enable);
    D3D8_TRACE("IDirect3DDevice8::LightEnable", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   LightEnable(%p, 0x%x, 0x%x) from %s\n", self, Index, Enable, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetLightEnable_c(void *self, uint32_t Index, void *pEnable)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetLightEnable((DWORD)Index, (WINBOOL *)pEnable);
    D3D8_TRACE("IDirect3DDevice8::GetLightEnable", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetLightEnable(%p, 0x%x, %p) from %s\n", self, Index, pEnable, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetClipPlane_c(void *self, uint32_t index, void *plane)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetClipPlane((DWORD)index, (const float *)plane);
    D3D8_TRACE("IDirect3DDevice8::SetClipPlane", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetClipPlane(%p, 0x%x, %p) from %s\n", self, index, plane, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetClipPlane_c(void *self, uint32_t Index, void *pPlane)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetClipPlane((DWORD)Index, (float *)pPlane);
    D3D8_TRACE("IDirect3DDevice8::GetClipPlane", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetClipPlane(%p, 0x%x, %p) from %s\n", self, Index, pPlane, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetRenderState_c(void *self, uint32_t State, uint32_t Value)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetRenderState((D3DRENDERSTATETYPE)State, (DWORD)Value);
    D3D8_TRACE("IDirect3DDevice8::SetRenderState", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetRenderState(%p, 0x%x, 0x%x) from %s\n", self, State, Value, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetRenderState_c(void *self, uint32_t State, void *pValue)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetRenderState((D3DRENDERSTATETYPE)State, (DWORD *)pValue);
    D3D8_TRACE("IDirect3DDevice8::GetRenderState", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetRenderState(%p, 0x%x, %p) from %s\n", self, State, pValue, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_BeginStateBlock_c(void *self)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->BeginStateBlock();
    D3D8_TRACE("IDirect3DDevice8::BeginStateBlock", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   BeginStateBlock(%p) from %s\n", self, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_EndStateBlock_c(void *self, void *pToken)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->EndStateBlock((DWORD *)pToken);
    D3D8_TRACE("IDirect3DDevice8::EndStateBlock", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   EndStateBlock(%p, %p) from %s\n", self, pToken, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_ApplyStateBlock_c(void *self, uint32_t Token)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->ApplyStateBlock((DWORD)Token);
    D3D8_TRACE("IDirect3DDevice8::ApplyStateBlock", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   ApplyStateBlock(%p, 0x%x) from %s\n", self, Token, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CaptureStateBlock_c(void *self, uint32_t Token)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->CaptureStateBlock((DWORD)Token);
    D3D8_TRACE("IDirect3DDevice8::CaptureStateBlock", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CaptureStateBlock(%p, 0x%x) from %s\n", self, Token, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_DeleteStateBlock_c(void *self, uint32_t Token)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->DeleteStateBlock((DWORD)Token);
    D3D8_TRACE("IDirect3DDevice8::DeleteStateBlock", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   DeleteStateBlock(%p, 0x%x) from %s\n", self, Token, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CreateStateBlock_c(void *self, uint32_t Type, void *pToken)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->CreateStateBlock((D3DSTATEBLOCKTYPE)Type, (DWORD *)pToken);
    D3D8_TRACE("IDirect3DDevice8::CreateStateBlock", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CreateStateBlock(%p, 0x%x, %p) from %s\n", self, Type, pToken, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetClipStatus_c(void *self, void *clip_status)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetClipStatus((const D3DCLIPSTATUS8 *)clip_status);
    D3D8_TRACE("IDirect3DDevice8::SetClipStatus", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetClipStatus(%p, %p) from %s\n", self, clip_status, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetClipStatus_c(void *self, void *pClipStatus)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetClipStatus((D3DCLIPSTATUS8 *)pClipStatus);
    D3D8_TRACE("IDirect3DDevice8::GetClipStatus", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetClipStatus(%p, %p) from %s\n", self, pClipStatus, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetTexture_c(void *self, uint32_t Stage, void *ppTexture)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DBaseTexture8 *out_ppTexture = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetTexture((DWORD)Stage, ppTexture ? &out_ppTexture : nullptr);
    if (ppTexture) wr32(ppTexture, d3d8_wrap(out_ppTexture));
    D3D8_TRACE("IDirect3DDevice8::GetTexture", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetTexture(%p, 0x%x, %p) from %s\n", self, Stage, ppTexture, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetTexture_c(void *self, uint32_t Stage, void *pTexture)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetTexture((DWORD)Stage, d3d8_unwrap<IDirect3DBaseTexture8>(pTexture));
    D3D8_TRACE("IDirect3DDevice8::SetTexture", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetTexture(%p, 0x%x, %p) from %s\n", self, Stage, pTexture, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetTextureStageState_c(void *self, uint32_t Stage, uint32_t Type, void *pValue)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetTextureStageState((DWORD)Stage, (D3DTEXTURESTAGESTATETYPE)Type, (DWORD *)pValue);
    D3D8_TRACE("IDirect3DDevice8::GetTextureStageState", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetTextureStageState(%p, 0x%x, 0x%x, %p) from %s\n", self, Stage, Type, pValue, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetTextureStageState_c(void *self, uint32_t Stage, uint32_t Type, uint32_t Value)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetTextureStageState((DWORD)Stage, (D3DTEXTURESTAGESTATETYPE)Type, (DWORD)Value);
    D3D8_TRACE("IDirect3DDevice8::SetTextureStageState", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetTextureStageState(%p, 0x%x, 0x%x, 0x%x) from %s\n", self, Stage, Type, Value, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_ValidateDevice_c(void *self, void *pNumPasses)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->ValidateDevice((DWORD *)pNumPasses);
    D3D8_TRACE("IDirect3DDevice8::ValidateDevice", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   ValidateDevice(%p, %p) from %s\n", self, pNumPasses, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetInfo_c(void *self, uint32_t DevInfoID, void *pDevInfoStruct, uint32_t DevInfoStructSize)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetInfo((DWORD)DevInfoID, (void *)pDevInfoStruct, (DWORD)DevInfoStructSize);
    D3D8_TRACE("IDirect3DDevice8::GetInfo", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetInfo(%p, 0x%x, %p, 0x%x) from %s\n", self, DevInfoID, pDevInfoStruct, DevInfoStructSize, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetPaletteEntries_c(void *self, uint32_t palette_idx, void *entries)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPaletteEntries((UINT)palette_idx, (const PALETTEENTRY *)entries);
    D3D8_TRACE("IDirect3DDevice8::SetPaletteEntries", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPaletteEntries(%p, 0x%x, %p) from %s\n", self, palette_idx, entries, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetPaletteEntries_c(void *self, uint32_t PaletteNumber, void *pEntries)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPaletteEntries((UINT)PaletteNumber, (PALETTEENTRY *)pEntries);
    D3D8_TRACE("IDirect3DDevice8::GetPaletteEntries", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPaletteEntries(%p, 0x%x, %p) from %s\n", self, PaletteNumber, pEntries, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetCurrentTexturePalette_c(void *self, uint32_t PaletteNumber)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetCurrentTexturePalette((UINT)PaletteNumber);
    D3D8_TRACE("IDirect3DDevice8::SetCurrentTexturePalette", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetCurrentTexturePalette(%p, 0x%x) from %s\n", self, PaletteNumber, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetCurrentTexturePalette_c(void *self, void *PaletteNumber)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetCurrentTexturePalette((UINT *)PaletteNumber);
    D3D8_TRACE("IDirect3DDevice8::GetCurrentTexturePalette", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetCurrentTexturePalette(%p, %p) from %s\n", self, PaletteNumber, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_DrawPrimitive_c(void *self, uint32_t PrimitiveType, uint32_t StartVertex, uint32_t PrimitiveCount)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->DrawPrimitive((D3DPRIMITIVETYPE)PrimitiveType, (UINT)StartVertex, (UINT)PrimitiveCount);
    D3D8_TRACE("IDirect3DDevice8::DrawPrimitive", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   DrawPrimitive(%p, 0x%x, 0x%x, 0x%x) from %s\n", self, PrimitiveType, StartVertex, PrimitiveCount, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_DrawIndexedPrimitive_c(void *self, uint32_t PrimitiveType, uint32_t minIndex, uint32_t NumVertices, uint32_t startIndex, uint32_t primCount)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->DrawIndexedPrimitive((D3DPRIMITIVETYPE)PrimitiveType, (UINT)minIndex, (UINT)NumVertices, (UINT)startIndex, (UINT)primCount);
    D3D8_TRACE("IDirect3DDevice8::DrawIndexedPrimitive", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   DrawIndexedPrimitive(%p, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x) from %s\n", self, PrimitiveType, minIndex, NumVertices, startIndex, primCount, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_DrawPrimitiveUP_c(void *self, uint32_t primitive_type, uint32_t primitive_count, void *data, uint32_t stride)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->DrawPrimitiveUP((D3DPRIMITIVETYPE)primitive_type, (UINT)primitive_count, (const void *)data, (UINT)stride);
    D3D8_TRACE("IDirect3DDevice8::DrawPrimitiveUP", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   DrawPrimitiveUP(%p, 0x%x, 0x%x, %p, 0x%x) from %s\n", self, primitive_type, primitive_count, data, stride, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_DrawIndexedPrimitiveUP_c(void *self, uint32_t primitive_type, uint32_t min_vertex_idx, uint32_t vertex_count, uint32_t primitive_count, void *index_data, uint32_t index_format, void *data, uint32_t stride)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->DrawIndexedPrimitiveUP((D3DPRIMITIVETYPE)primitive_type, (UINT)min_vertex_idx, (UINT)vertex_count, (UINT)primitive_count, (const void *)index_data, (D3DFORMAT)index_format, (const void *)data, (UINT)stride);
    D3D8_TRACE("IDirect3DDevice8::DrawIndexedPrimitiveUP", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   DrawIndexedPrimitiveUP(%p, 0x%x, 0x%x, 0x%x, 0x%x, %p, 0x%x, %p, 0x%x) from %s\n", self, primitive_type, min_vertex_idx, vertex_count, primitive_count, index_data, index_format, data, stride, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_ProcessVertices_c(void *self, uint32_t SrcStartIndex, uint32_t DestIndex, uint32_t VertexCount, void *pDestBuffer, uint32_t Flags)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->ProcessVertices((UINT)SrcStartIndex, (UINT)DestIndex, (UINT)VertexCount, d3d8_unwrap<IDirect3DVertexBuffer8>(pDestBuffer), (DWORD)Flags);
    D3D8_TRACE("IDirect3DDevice8::ProcessVertices", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   ProcessVertices(%p, 0x%x, 0x%x, 0x%x, %p, 0x%x) from %s\n", self, SrcStartIndex, DestIndex, VertexCount, pDestBuffer, Flags, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CreateVertexShader_c(void *self, void *declaration, void *byte_code, void *shader, uint32_t usage)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->CreateVertexShader((const DWORD *)declaration, (const DWORD *)byte_code, (DWORD *)shader, (DWORD)usage);
    D3D8_TRACE("IDirect3DDevice8::CreateVertexShader", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CreateVertexShader(%p, %p, %p, %p, 0x%x) from %s\n", self, declaration, byte_code, shader, usage, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetVertexShader_c(void *self, uint32_t Handle)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetVertexShader((DWORD)Handle);
    D3D8_TRACE("IDirect3DDevice8::SetVertexShader", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetVertexShader(%p, 0x%x) from %s\n", self, Handle, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetVertexShader_c(void *self, void *pHandle)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetVertexShader((DWORD *)pHandle);
    D3D8_TRACE("IDirect3DDevice8::GetVertexShader", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetVertexShader(%p, %p) from %s\n", self, pHandle, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_DeleteVertexShader_c(void *self, uint32_t Handle)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->DeleteVertexShader((DWORD)Handle);
    D3D8_TRACE("IDirect3DDevice8::DeleteVertexShader", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   DeleteVertexShader(%p, 0x%x) from %s\n", self, Handle, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetVertexShaderConstant_c(void *self, uint32_t reg_idx, void *data, uint32_t count)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetVertexShaderConstant((DWORD)reg_idx, (const void *)data, (DWORD)count);
    D3D8_TRACE("IDirect3DDevice8::SetVertexShaderConstant", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetVertexShaderConstant(%p, 0x%x, %p, 0x%x) from %s\n", self, reg_idx, data, count, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetVertexShaderConstant_c(void *self, uint32_t Register, void *pConstantData, uint32_t ConstantCount)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetVertexShaderConstant((DWORD)Register, (void *)pConstantData, (DWORD)ConstantCount);
    D3D8_TRACE("IDirect3DDevice8::GetVertexShaderConstant", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetVertexShaderConstant(%p, 0x%x, %p, 0x%x) from %s\n", self, Register, pConstantData, ConstantCount, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetVertexShaderDeclaration_c(void *self, uint32_t Handle, void *pData, void *pSizeOfData)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetVertexShaderDeclaration((DWORD)Handle, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DDevice8::GetVertexShaderDeclaration", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetVertexShaderDeclaration(%p, 0x%x, %p, %p) from %s\n", self, Handle, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetVertexShaderFunction_c(void *self, uint32_t Handle, void *pData, void *pSizeOfData)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetVertexShaderFunction((DWORD)Handle, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DDevice8::GetVertexShaderFunction", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetVertexShaderFunction(%p, 0x%x, %p, %p) from %s\n", self, Handle, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetStreamSource_c(void *self, uint32_t StreamNumber, void *pStreamData, uint32_t Stride)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetStreamSource((UINT)StreamNumber, d3d8_unwrap<IDirect3DVertexBuffer8>(pStreamData), (UINT)Stride);
    D3D8_TRACE("IDirect3DDevice8::SetStreamSource", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetStreamSource(%p, 0x%x, %p, 0x%x) from %s\n", self, StreamNumber, pStreamData, Stride, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetStreamSource_c(void *self, uint32_t StreamNumber, void *ppStreamData, void *pStride)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DVertexBuffer8 *out_ppStreamData = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetStreamSource((UINT)StreamNumber, ppStreamData ? &out_ppStreamData : nullptr, (UINT *)pStride);
    if (ppStreamData) wr32(ppStreamData, d3d8_wrap(out_ppStreamData));
    D3D8_TRACE("IDirect3DDevice8::GetStreamSource", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetStreamSource(%p, 0x%x, %p, %p) from %s\n", self, StreamNumber, ppStreamData, pStride, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetIndices_c(void *self, void *pIndexData, uint32_t BaseVertexIndex)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetIndices(d3d8_unwrap<IDirect3DIndexBuffer8>(pIndexData), (UINT)BaseVertexIndex);
    D3D8_TRACE("IDirect3DDevice8::SetIndices", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetIndices(%p, %p, 0x%x) from %s\n", self, pIndexData, BaseVertexIndex, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetIndices_c(void *self, void *ppIndexData, void *pBaseVertexIndex)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    IDirect3DIndexBuffer8 *out_ppIndexData = nullptr;
    uint32_t r = (uint32_t)(uintptr_t)obj->GetIndices(ppIndexData ? &out_ppIndexData : nullptr, (UINT *)pBaseVertexIndex);
    if (ppIndexData) wr32(ppIndexData, d3d8_wrap(out_ppIndexData));
    D3D8_TRACE("IDirect3DDevice8::GetIndices", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetIndices(%p, %p, %p) from %s\n", self, ppIndexData, pBaseVertexIndex, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_CreatePixelShader_c(void *self, void *byte_code, void *shader)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->CreatePixelShader((const DWORD *)byte_code, (DWORD *)shader);
    D3D8_TRACE("IDirect3DDevice8::CreatePixelShader", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   CreatePixelShader(%p, %p, %p) from %s\n", self, byte_code, shader, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetPixelShader_c(void *self, uint32_t Handle)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPixelShader((DWORD)Handle);
    D3D8_TRACE("IDirect3DDevice8::SetPixelShader", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPixelShader(%p, 0x%x) from %s\n", self, Handle, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetPixelShader_c(void *self, void *pHandle)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPixelShader((DWORD *)pHandle);
    D3D8_TRACE("IDirect3DDevice8::GetPixelShader", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPixelShader(%p, %p) from %s\n", self, pHandle, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_DeletePixelShader_c(void *self, uint32_t Handle)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->DeletePixelShader((DWORD)Handle);
    D3D8_TRACE("IDirect3DDevice8::DeletePixelShader", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   DeletePixelShader(%p, 0x%x) from %s\n", self, Handle, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_SetPixelShaderConstant_c(void *self, uint32_t reg_idx, void *data, uint32_t count)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->SetPixelShaderConstant((DWORD)reg_idx, (const void *)data, (DWORD)count);
    D3D8_TRACE("IDirect3DDevice8::SetPixelShaderConstant", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   SetPixelShaderConstant(%p, 0x%x, %p, 0x%x) from %s\n", self, reg_idx, data, count, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetPixelShaderConstant_c(void *self, uint32_t Register, void *pConstantData, uint32_t ConstantCount)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPixelShaderConstant((DWORD)Register, (void *)pConstantData, (DWORD)ConstantCount);
    D3D8_TRACE("IDirect3DDevice8::GetPixelShaderConstant", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPixelShaderConstant(%p, 0x%x, %p, 0x%x) from %s\n", self, Register, pConstantData, ConstantCount, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_GetPixelShaderFunction_c(void *self, uint32_t Handle, void *pData, void *pSizeOfData)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->GetPixelShaderFunction((DWORD)Handle, (void *)pData, (DWORD *)pSizeOfData);
    D3D8_TRACE("IDirect3DDevice8::GetPixelShaderFunction", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   GetPixelShaderFunction(%p, 0x%x, %p, %p) from %s\n", self, Handle, pData, pSizeOfData, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_DrawRectPatch_c(void *self, uint32_t handle, void *segment_count, void *patch_info)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->DrawRectPatch((UINT)handle, (const float *)segment_count, (const D3DRECTPATCH_INFO *)patch_info);
    D3D8_TRACE("IDirect3DDevice8::DrawRectPatch", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   DrawRectPatch(%p, 0x%x, %p, %p) from %s\n", self, handle, segment_count, patch_info, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_DrawTriPatch_c(void *self, uint32_t handle, void *segment_count, void *patch_info)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->DrawTriPatch((UINT)handle, (const float *)segment_count, (const D3DTRIPATCH_INFO *)patch_info);
    D3D8_TRACE("IDirect3DDevice8::DrawTriPatch", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   DrawTriPatch(%p, 0x%x, %p, %p) from %s\n", self, handle, segment_count, patch_info, guest_caller());
    return r;
}

EXTERN_C uint32_t IDirect3DDevice8_DeletePatch_c(void *self, uint32_t Handle)
{
    IDirect3DDevice8 *obj = d3d8_native<IDirect3DDevice8>(self);
    uint32_t r = (uint32_t)(uintptr_t)obj->DeletePatch((UINT)Handle);
    D3D8_TRACE("IDirect3DDevice8::DeletePatch", r);
    if (d3d8_trace_level() >= 3) fprintf(stderr, "d3d8:   DeletePatch(%p, 0x%x) from %s\n", self, Handle, guest_caller());
    return r;
}
