# Command & Conquer Generals Zero Hour, native arm64 macOS port (pilot).
# The build rules are shared: see common/native-mac/mk/game.mk.
COMMON := ../../../common/native-mac
include $(COMMON)/mk/game.mk
